endlessm/gnome-shell

- debian/gnome-shell.install
- debian/rules
We disable extensions, so let's save some bits by disabling this plugin.
https://phabricator.endlessm.com/T12044
> Disable the browser plugin, only useful for extensions.gnome.org

- data/org.gnome.shell.gschema.xml.in
- data/theme/gnome-shell.css
- js/gdm/loginDialog.js
- js/js-resources.gresource.xml
- js/ui/forceAppExitDialog.js
- js/ui/layout.js
- js/ui/legacyTray.js
- js/ui/messageTray.js
- js/ui/modalDialog.js
- js/ui/monitor.js
- js/ui/osdWindow.js
- js/ui/overview.js
- js/ui/screenShield.js
- js/ui/unlockDialog.js
- js/ui/windowManager.js
- po/POTFILES.in
This PR also includes another commit necessary for this, since otherwise GNOME Shell will throw an error when trying to create the ForceAppExitDialog class due to circular imports problem:
Since modalDialog.js imports layout.js, which ends up getting windowManager.js imported, which imports forceAppExitDialog.js... which imports modalDialog.js again, at the time that the ForceAppExitDialog class is being created its super class is not completely defined yet, causing the constructor of the ModalDialog not to be called and therefore the whole thing to fail.
The first commit addresses that problem (which would get worse with GJS 1.48) by splitting out Monitor and MonitorConstraint out of layout.js, as those are the classes typically used in most places, preventing importing the whole …
> Add a dialog to force quit applications

- data/theme/gnome-shell.css
This patch makes the shell use Endless' Lato fonts instead of
the default Cantarell.
https://phabricator.endlessm.com/T17230
> theme: Use Endless' font face

- js/js-resources.gresource.xml
- js/ui/components/discoveryFeed.js
- js/ui/layout.js
- js/ui/main.js
- js/ui/sessionMode.js
- js/ui/sideComponent.js
- js/ui/windowManager.js
- src/shell-app-system.c
- src/shell-grid-desaturate-effect.c
Port the "side component" infrastructure to GNOME-Shell.
Note that the desktop overlay function isn't currently working. As far as I can tell, we are correctly creating the overlay window and also correctly setting the stage input region, but it does not seem to be capturing clicks. Not sure why.
https://phabricator.endlessm.com/T17236
> T17236 - Side components

- data/Makefile.am
- data/eos-link-feedback.desktop.in.in
This desktop file was present in our previous Endless
Shell before the rebase.
This commit brings this desktop file back.
https://phabricator.endlessm.com/T16842
> project: Add eos-link-feedback back

- js/ui/watermark.js
When running under a GDM session, Shell has no background
manager instances available, and the watermark code would
make it crash.
Fix that by checking if there are background managers.
https://phabricator.endlessm.com/T15839
> watermak: Protect against null background managers

- js/ui/status/system.js
We cannot know which label will be the widest, and thus
assuming that the logout button is the widest button is
just plain wrong.
This commit fixes this by using the widest button width
instead of the logout button.
https://phabricator.endlessm.com/T17435
> status: Use the widest button width instead of logout

- data/theme/gnome-shell-high-contrast.css
- data/theme/gnome-shell.css
- js/ui/panel.js
The solid black top bar we currently use works well for maximized
or tiled windows, as it puts focus on the application content by
blending into the monitor bezel. However it also visually reduces
the screen space, which is particularly noticeable when no window
is located nearby. Having the top bar blend with the background is
a better option in that case, so track window positions and add
some transparency when the top bar is free-floating.
https://bugzilla.gnome.org/show_bug.cgi?id=747163
https://phabricator.endlessm.com/T17505
> panel: Add transparency when free-floating

- data/theme/gnome-shell.css
It will be very large and bright without it.
https://phabricator.endlessm.com/T17482
> theme: add missing style selector for AppIconBarNavButton

- js/ui/status/power.js
Instead of using the shutdown icon, since we don't have a shutdown
option inside this menu anymore.
https://phabricator.endlessm.com/T17362
> power: hide indicator when not on battery

- data/theme/gnome-shell.css
- js/ui/endlessButton.js
When the tooltip is set, it blindly calculates the position
using zero as the horizontal axis basis. This assumption can
be false for example when the underscan compensation is in
place, leading to a tooltip label in the wrong horizontal
position.
Fix that by considering the monitor position when calculating
the tooltip position.
https://phabricator.endlessm.com/T17506
> endless: consider monitor position when placing tooltip

- configure.ac
- data/org.gnome.shell.gschema.xml.in
- js/ui/windowManager.js
- src/Makefile.am
- src/wobbly-effect.cpp
- src/wobbly-effect.h
Link to libendless_wobbly (from libwobbly) and add a new
EndlessShellFXWobbly class to bridge between a clutter effect
and the wobbly::Model/wobbly::Anchor.
Use endless_shell_fx_wobbly_grab to grab a point on the mesh
and move it around.
Use endless_shell_fx_wobbly_ungrab to release a point on the mesh.
Each of the above functions may only be called once whilst in the
opposing state and cannot be called again whilst in the same state.
EOSShellWobbly is a JavaScript subclass of EndlessShellFXWobbly
which handles integration between the shell itself and the wobbly
effect. It provides API to handle mouse grab / ungrab of a window
and window movement whilst grabbed.
Provide the following new keys in org.gnome.shell:
'wobbly-spring-k' : Spring K
'wobbly-spring-friction' : Spring Friction …
> windowManager: Add wobbly windows.

- data/theme/gnome-shell.css
The Endless button's hover state was applied only when the
bottom bar was semi-transparent because it was missing a
selector to apply the same color when the bottom bar was
fully opaque.
Fix that by adding the hover state to #panel.solid selector
as well.
https://phabricator.endlessm.com/T17521
> theme: Add selector for solid bottom bar

- js/Makefile.am
- js/misc/config.js.in
This small change that I overlooked while porting other changes
makes it possible to visualize the default desktop's icon grid
when no customizations have been done before at all by the user.
In other words, it makes the desktop grid to show up on newly
flashed images which otherwise would fail to load the defaults.
https://phabricator.endlessm.com/T17653
> config: Properly define DATADIR, PKGDATADIR and LOCALSTATEDIR

- js/ui/userMenu.js
Yelp desktop file was renamed from yelp.desktop to org.gnome.Yelp.desktop
to make yelp application D-Bus launchable.
First we should merge https://github.com/endlessm/yelp/pull/40.
https://phabricator.endlessm.com/T10165
> js: rename yelp desktop file

- js/ui/appDisplay.js
- js/ui/layout.js
- js/ui/overview.js
- js/ui/viewSelector.js
- js/ui/workspaceMonitor.js
This PR moves a few things around to make it possible to create a ClutterClone of the ClutterActor that holds the desktop's grid, following the lead of existing code in eos-desktop, but adapted to the new shell.
https://phabricator.endlessm.com/T17662
> Implement desktop's clones to show underneath visible windows 

- data/theme/gnome-shell.css
We don't want this as we need perfect alignment.
> theme: Remove spacing between elements in overview

- js/ui/endlessButton.js
When viewing apps, the hover label should read "Show Desktop",
and while viewing the desktop, the hover label should read
"Show Apps".
https://phabricator.endlessm.com/T17520
> endlessButton: Change hover label according to current view

- data/theme/gnome-shell.css
- js/js-resources.gresource.xml
- js/ui/appDisplay.js
- js/ui/editableLabel.js
- js/ui/iconGrid.js
- src/shell-app.c
- src/shell-app.h
Previously, Endless OS shell allowed users to rename
the desktop icons and folders. With the GNOME Shell
rebase, however, that feature was lost and we cannot
rename them anymore.
This commit brings back the code to edit desktop icons
and folders, and adapts the previous work over the
rebased GNOME Shell so that only desktop icons and
folders are editable (and e.g. search results are not).
https://phabricator.endlessm.com/T17660
> shell: Allow editing desktop icon names

- data/theme/gnome-shell.css
According to Robin, this should be RGBa(0, 0, 0, 0.3) now.
https://phabricator.endlessm.com/T17657
> css: Make the background of the folder popup darker

- data/theme/gnome-shell.css
The folder icons had a gray background that encompassed the icon and
label which made it looked too different from the regular app icons.
These changes add a rounded corner square that includes only the tiny
icons of the folder which makes it look much closer to a regular app
icon.
https://phabricator.endlessm.com/T17785
> icon-grid: Style the folder icons to look closer to app icons

- js/ui/appDisplay.js
`eosinstaller` images do not have the app center. Ideally we should arrange for `enable-app-center` to be `false` in GSettings, but we should still not crash if it's `true`.
https://phabricator.endlessm.com/T17875
> appDisplay: don't crash if app center isn't installed

- js/ui/appDisplay.js
- js/ui/workspace.js
- js/ui/workspaceMonitor.js
- src/shell-app.c
Besides that change (last commit), this PR also a fix from upstream to silent a critical error that happens when closing windows, a cherry pick of a AppActivation-related patch missed during the rebase, and a fix for the way the property hasActiveWindows gets computed.
https://phabricator.endlessm.com/T17496
> Add integration with AppActivation from the grid

- js/ui/iconGridLayout.js
This was fixed in the pre-rebase shell --
https://github.com/endlessm/eos-desktop/pull/266 -- but was lost in the
rebase.
https://phabricator.endlessm.com/T15704
> Move eos-image-defaults to /var/lib

- data/org.gnome.shell.gschema.xml.in
These defaults are taken from [the "taskbar-pins" key in `eos-desktop`](https://github.com/endlessm/eos-desktop/blob/ee7659e61a5dcb804065b107f68ca3b81ce1f10c/data/org.gnome.shell.gschema.xml.in.in#L223-L230), the fork of GNOME Shell used in Endless OS 3.1 and earlier.
Migrating users' existing taskbar icons from the now-obsolute "taskbar-pins" setting on upgrade is already implemented, but without this change new users would receive the upstream defaults. In particular, since we do not ship epiphany, this meant users would not have a browser on the taskbar.
https://phabricator.endlessm.com/T17622
> Restore Endless-specific default taskbar icons

- js/ui/screenShield.js
Upon releasing the mouse, if there was no drag motion,
lift the shield.  If there is any drag motion, only lift
the shield if the original drag threshold was achieved.
Many novice users are confused by the need to drag the shield open,
so we make it as easy as possible at the expense that touchscreen
users may unintentionally lift the shield with a stray screen touch.
https://phabricator.endlessm.com/T17550
> screenShield: lift the shield if user clicks without dragging

- js/ui/shellEntry.js
Make sure the spinner is stopped whenever the search is stopped.
Previously, it was easy to get into a state where the spinner
would keep running and cause CPU churn.
https://phabricator.endlessm.com/T17855
> shellEntry: ensure that search spinner stops

- js/ui/windowManager.js
found in the logs from: https://phabricator.endlessm.com/T17959
> windowManager: Missing Gdk import

- js/ui/appDisplay.js
This PR makes the necessary changes to add this option to both apps and folders while keeping most of the app-specific entries in the contextual menu. Only exceptions are "Show details" and "Add/Remove to/from favourites" which are hidden for convenience.
Note: The only commits relevant from this PR are the **last 4 ones**, the rest of them belong to PR #78 which should be merged prior to this one.
https://phabricator.endlessm.com/T18013
> Allow removing desktop icons from the contextual menu

- js/ui/viewSelector.js
The spinner is being set whenever the search-progress-updated signal is
received, and then uses the .searchInProgress property to determine whether
to spin or not, but the problem is that this property is being set from
multiple places, so sometimes we can end in a race condition that ends up
with the callback being called with no text in the entry but still the
searchResults object reporting that it's searching.
When this happens, the spinner enters a state where it's constantly
spinning, consuming lots of CPU for no reason unless some user initiated
action takes it out of that state.
Probably not a real fix, but let's at least prevent this situation from
happening by double checking that there's something to search before
setting the spinner on fire. …
> viewSelector: Don't set the spinner on when there are nothing to search

- js/ui/appDisplay.js
It's still possible to add/remove apps to/from a folder, but reordering
apps inside a given folder is currently causing a crash that we sadly
don't have more time to investigate for now (will do for the next release).
https://phabricator.endlessm.com/T18025
> appDisplay: Temporarily disabling DnD of applications inside a folder

- js/ui/components/updaterManager.js
Upstream removed this functionality from the login manager.
Replace with the equivalent remote call on the session manager.
https://phabricator.endlessm.com/T17956
> updateManager: fix call to reboot

- data/theme/gnome-shell.css
Removes some stray CSS that did not seem to be helpful
and instead caused the folder icons to appear misaligned
relative to the app icons.
https://phabricator.endlessm.com/T17824
> Fix folder icon alignment on grid

- js/ui/appDisplay.js
The override FolderIcon provides for getDragActor() is harmful, as the
base class already has the right logic we need.
> appDisplay: use right actor when dragging

- data/theme/gnome-shell.css
- js/ui/iconGrid.js
The icon labels' width was too short for many app names to fit it, and
thus the grid showed more apps with ellipsized names than in the shell
we had in < 3.2 versions.
https://phabricator.endlessm.com/T18044
> iconGrid: Increase the labels width

- debian/gnome-shell.gsettings-override
We now specify this from the master branch (see commit 6f5e31dd) so
we don't need to do this again via an override. Also, it's not only
that's not needed but also that keeping this in place is harmful,
since it would break set ups like the live installer where we patch
the defaults via other means, as this override file will then be
applied, rendering those other customizations useless.
https://phabricator.endlessm.com/T17622
> Remove GSettings schema override from debian package

- js/ui/workspace.js
- js/ui/workspaceMonitor.js
- src/shell-app.c
- src/shell-window-tracker.c
- src/shell-window-tracker.h
The actual fix for this issue is 8b7a25f7 ("ShellApp: Consider speedwagon windows as 'not interesting' for a given app"), but this PR also proposes a few related commits more that fix issues related to app activation (unveiled after fixing this problem) along with backporting a few (also related) patches that got lost during the rebase process.
https://phabricator.endlessm.com/T17937
> Prevent hiding app main window when speedwagon is gone 

- js/ui/remoteSearch.js
Due to a bug in the flatpak builds, we have been accidentally
appending the search-provider.ini files with "DefaultDisabled=true".
This causes the default behavior for Endless apps to have
search disabled unless explicitly enabled in a gsetting.
Since global search of Endless apps is an important feature
of our OS, we include a hack here to pretend that Endless apps
(app ID starting with "com.endlessm.") do not set this flag.
While the proper fix is to fix the flatpak builder,
rebundle all Endless flatpaks, and update all Endless flatpaks
installed on user machines, that is a huge endeavor and not
something we can quickly patch, so we should live with this
hack for a while until we have fixed our latest flatpaks
and given users plenty of time to have updated all their apps.
We did not …
> remoteSearch: ignore DefaultDisabled for Endless apps

- js/ui/appDisplay.js
It's very confusing when the user switches between the windows view and
the grid and the latter always moves to the first page, no matter which
had it was on before.
This is being deliberately done in the code from upstream because in the
case of the upstream shell the user toggles the apps view more directly
than in EOS, and thus it makes sense to reset the view to show the first
page there. So this patch just removes the mentioned code.
https://phabricator.endlessm.com/T17979
> appDisplay: Don't get the grid to the first page on hide

- js/ui/remoteSearch.js
The reason for this is that showing the search results in an app can
take some time, and thus its speedwagon should be shown if needed (which
accomplished by activating the app context).
https://phabricator.endlessm.com/T3968
> search: Activate the app context before the result

- docs/reference/shell/Makefile.am
- docs/reference/st/Makefile.am
- src/Makefile.am
This is a workaround for a change in behaviour in binutils, which we're basically bringing from the debian/rules file right into the autotools sources, with the hope of getting it merged upstream too.
https://phabricator.endlessm.com/T18131
> Fix Jenkins build: use RPATH instead of RUNPATH for ELF binaries

- debian/rules
We know apply the --disable-new-dtags flag for the linker right from
the autotools sources, so we can remove this one from here.
https://phabricator.endlessm.com/T18131
> debian/rules: Remove work around for binutils behaviour change

- js/ui/remoteSearch.js
This should be squashed with f5dc86c3 in future rebases.
https://phabricator.endlessm.com/T4008
> remoteSearch: sort providers for apps on the desktop before

- js/ui/focusCaretTracker.js
The first time that the session is started, it can happen that the
AT SPI hasn't been correctly initialized, and this results in a crash
when attempting to register the caret or focus listeners.
In order to avoid this, these changes check the result of initializing
the AT SPI, to allow further attempts when it has failed.
https://phabricator.endlessm.com/T18273
> Fix crash when using the magnifier

- debian/rules
Apparently, even though the changes made in the master branch allowed us
to build the shell using the new behaviour in the build time linker (that
now uses DT_RUNPATH instead of DT_RPATH), that is not a complete solution
since the shell will fail to find the shared objects wrapped by private
introspected libraries (e.g. ShellMenu-0.1.gir), as they live in the non
standard & private /usr/lib/gnome-shell directory.
So, this is sad an ugly but, as I was not able to figure out yet a way
to have the GIR scanner & compiler generating the bindings in a way that
they will find those private shared objects at runtime, I'm proposing to
revert here to Debian's current strategy of using the old dtags when
linking (that is, using DT_RPATH again), that will make our shell run
again as this way the …
> Revert "debian/rules: Remove work around for binutils behaviour change"

- src/main.c
This is not strictly necessary when linking the shell with DT_RPATH as
the runtime path will be extracted from the introspected libraries and
used from gobject introspection to find them when loading them based on
the typelib files, but when linking with DT_RUNPATH, as it's the case
for some linkers (e.g. ld.gold, or ld.bfd in some distros like Debian).
By explicitly prepending this directory as a library path for GIR, we're
making sure that the wrapped shared objects can be found in all cases.
https://phabricator.endlessm.com/T18325
> main: Add $(pkglibdir) to GIR's list of search path for scanned libraries

- debian/rules
Turns out that we finally figured out (thanks @dbnicholson and @ptomato for your
help!) what the missing piece of the puzzle was in commit ec0f63ff, so there's
no need to build with --disable-new-dtags (now for real) now that we have patched
the master branch so that the shell builds AND runs just fine with DT_RUNPATH.
Sorry for the back and forth, but I think it's good to remove this workaround
from the code if possible, to remove papering over the actual problem.
This reverts commit 7fae4585 and should be squashed into it in future rebases.
https://phabricator.endlessm.com/T18325
> Revert "Revert "debian/rules: Remove work around for binutils behaviour change

- src/main.c
As it is setup now, the shell will work fine without this addition since
the shell will reach Mutter's private libraries through the usual loading
mechanisms, but adding it should make things more robust against potential
future changes, besides making it consistent with the similar calls to
g_irepository_prepend_search_path() right before these lines.
https://phabricator.endlessm.com/T18325
> main: Also add Mutter's private libdir to GIR's list of search paths

- js/ui/boxpointer.js
The second time a folder is opened, the arrow of the folder popup will
be shown in the wrong position (as if pushed to the left). This is due
to its transformed position, which is affected depending on the
allocation of the boxPointer's container.
This patch simply queues a repaint when the allocation is changed which
fixes the issue.
https://phabricator.endlessm.com/T17838
> boxPointer: Fix arrow's position the second time a folder is opened

- js/ui/windowManager.js
A call to add the SideComponent's actor to the list of actors being
destroyed was lost with the rebase due to the having the base code
refactored, which was causing the side component's actor to never
be completely destroyed.
This was often not visible because we only use left or top side
components now, but the problem could still be seen in setups with
multiple monitors where the main monitor is not in the leftmost
position, as the side component's actor would be left forever in
the leftmost screen after closing it.
https://phabricator.endlessm.com/T18137
> windowManager: Ensure SideComponent's actor gets properly destroyed

- js/ui/endlessButton.js
Previously, it was only monitoring the "page-changed" signal,
which was triggered only when the overview switched from
the icon grid to the window picker, and thus did not switch
back to "Show Desktop" when the app windows were displayed.
Note that we connect to the "showing" signal rather than "shown"
so that the label changes right away rather than waiting for
the overview animation to complete.
If we instead connected to "shown" and "hidden", we could have used
the overview's "visible" attribute to simplify the logic a little,
but the effect did not feel right in that the label would appear
to change instantly when hiding but delayed when showing.
https://phabricator.endlessm.com/T18327
> endlessButton: fix "Show Desktop" vs. "Show Apps" tooltip

- js/ui/endlessButton.js
We were adding the monitor's x position in the wrong place,
which mis-placed the label when the primary monitor is on the right.
https://phabricator.endlessm.com/T18565
> endlessButton: fix hover label location for dual display

- js/ui/iconGridLayout.js
- js/ui/shellDBus.js
This removes the old icon and inserts the new one in its place. We'll
use this from the app store in order to replace the "Get X" launchers
with the actual application once installed.
https://phabricator.endlessm.com/T18657
> iconGridLayout: Add ReplaceAppIfPossible method to ShellAppStore

- js/ui/appDisplay.js
Otherwise the smaller icons that are shown inside a folder's icon will
be too big and overflow out of its boundaries.
https://phabricator.endlessm.com/T18351
> Consider scale factor when creating the folders' subicons

- js/ui/userWidget.js
We need to regenerate the user's avatar in the bottom panel and the
user menu when the scaling factor changes, so that it's rendered
properly according to the factor in effect.
https://phabricator.endlessm.com/T18352
> Recreate the user's avatar when scaling factor changes

- js/ui/appIconBar.js
This fixes the clones being way too small when in High DPI mode.
https://phabricator.endlessm.com/T18851
> appIconBar: Consider scaling factor for windows clones

- js/ui/discoveryFeedButton.js
- js/ui/viewSelector.js
The viewSelector was making the feed button visible again when
it faded in all components by setting 'visible' directly. This
bypassed our resolution check. For some uninteresting reasons
we can't fix this by defining a setter on the visible property
(it seems like this is not supported for GObject properties
since that would also require a getter and get_property is
not introspectable). So add a new API and have the viewSelector
use that instead.
https://phabricator.endlessm.com/T18546
> feed: Add a changeVisbilityState to be used instead of visible

- configure.ac
- js/ui/environment.js
- src/Makefile.am
In mutter's commit 4ebc55f2 libmutter.so and the mutter-*.so libraries
were made parallel installable [1] which, among other things, impacted
the filenames of the shared objects and .pc files that get installed.
GNOME Shell 3.24 is already adapted to this situation (see [2]), so
we need this small fix here to keep our fork of GNOME Shell 3.22
building and running find with the newer version of mutter.
[1] https://git.gnome.org/browse/mutter/commit/?id=4ebc55f2
[2] https://git.gnome.org/browse/gnome-shell/commit/?id=a46ea3f8
https://phabricator.endlessm.com/T18787
> Adapt to the new filenames and versions of mutter and its private libraries

- js/ui/backgroundMenu.js
- js/ui/sideComponent.js
- js/ui/windowManager.js
We assumed that all side components would have a y-coordinate that
was visible on screen and positioned the overlay relative to
that y-coordinate. That didn't work in the case of the discovery
feed because it starts off-screen and the overlay window's position
never got updated. We should update the geometry of the overlay
at the same time as rebuilding the overlay capture region.
Also, we were only making the overlay as large as the distance
between the left hand side of the monitor and the left hand
side of the side component window. This didn't make much sense
considering that the overlay region for the shell already blocked
out the side component window anyway and broke in the case
of the discovery feed, because the feed is in the center
of the screen. …
> windowManager: Make sure to update overlay geometry on sideComponent changes

- js/ui/remoteSearch.js
We already call the remote search method to activate the app; don't
activate it again by calling activate() on the AppActivationContext.
https://phabricator.endlessm.com/T18669
> remoteSearch: don't activate the app twice

- js/ui/appDisplay.js
Previously we were keeping the "seen" apps in a separate set, but
we were only ever considering those returned as results for the given
string; the app that is supposed to replace the launcher may not match
the given string at all.
Fix it by simply checking whether the replacement is installed directly.
https://phabricator.endlessm.com/T18771
> appDisplay: avoid "Get X" apps showing in search

- data/Makefile.am
Per Cosimo Cecchi, the rules file belongs under /usr/share/
rather than /etc/, since it is not a distributor override.
This was missed when we rebased on gnome-shell 3.22.
https://phabricator.endlessm.com/T19035
> Move 40-gdm.rules to $(datadir)

- debian/gnome-shell-common.install
Needed for 40-gdm.rules, which was missing from the gnome-shell
3.22 rebase, and thus had effectively disabled password resets.
https://phabricator.endlessm.com/T19035
> Install /usr/share/polkit-1

- js/ui/appDisplay.js
That animation doesn't feel right when opening a folder with many
apps inside, specially on slow computers where we skip many frames.
https://phabricator.endlessm.com/T18330
> appDisplay: Don't animate icons one by one when opening a folder

- src/shell-gtk-embed.c
If a tray icon gets a mapped and unmapped and the mapped again
in quick succession, we can end up with multiple handlers
listening for window creation events.
This commit tries to guard against that by only listening for
window-created events when we don't  know the actor associated
with the icon.
https://bugzilla.gnome.org/show_bug.cgi?id=787361
> gtk-embed: ensure we only listen for window-created events once

- js/ui/dnd.js
- src/shell-app.c
This PRs drops a patch that is no longer needed in 3.24 and replaces another one with the right implementation, already landed upstream.
https://phabricator.endlessm.com/T19421
> Align patches with upstream

- src/shell-app.c
This broke during the rebases to 3.22 and 3.24, so let's pick this patch again and drop the one with "leftovers" after squashing so many things during the rebases.
https://phabricator.endlessm.com/T19424
> Fix closing Speedwagon quickly before the app starts

- data/theme/gnome-shell.css
- js/ui/screenShield.js
As per the design spec, we want to use the Metropolis font for
the clock actor, tweak a bit the text's color and opacity and
also ensure that the box for the vertical arrows gets vertically
centered between the bottom of the clock's actor and the top of
the task bar.
https://phabricator.endlessm.com/T19165
> screenShield: Style the clock actor and center vertical arrows

- js/ui/viewSelector.js
This commit is actually "Fix broken transitions between pages in
overview modes" (09e8fd6b) from the 3.22 version of our shell,
which got lost somehow during the 3.24 rebase.
This caused the problem of having the desktop locking up mainly due
to a missing call to workspacesDisplay.hide() in viewSelector:hide(),
which was initially removed in commit 1ed19818, and then fix by this
other commit that never made it to our 3.24 shell.
Thus, this commit should be squashed along with 91cd581f (it's just
a revert of that one) and 5b241cec during the next rebase.
https://phabricator.endlessm.com/T17817
> viewSelector: Fix lock-ups when printing from the certain apps

- src/shell-app.c
It turns out that this fix broke our eos-google-chrome-helper mechanism (T19684):
It will cause the Chrome fake "app" (the one that opens the App Center when Chrome
is not installed) to be permanently moved to the STARTING state after running it
once, causing the speedwagon to never go away until hitting the timeout if you
choose not to install it when the App Center opens.
Since the problem with Speedwagon this ticket was supposed to fix is not strictly
speaking a regression (it's been there for a while), we're temporarily reverting
this patch so that Chrome is not broken at least.
This reverts commit 3c27b824053ec4bc55fdd155365c801abeb1b4ff.
https://phabricator.endlessm.com/T19424
https://phabricator.endlessm.com/T19684
> Revert "shell-app: Don't transition to STOPPED while still in the STARTING state"

- js/ui/shellDBus.js
This pollutes the metrics server due to apps like Chrome, which already
have an icon in the desktop even before being actually instelled-
https://phabricator.endlessm.com/T19717
> shellDBus: Don't send metric on AddAppIfNotVisible for IDs in the desktop

- js/ui/layout.js
- js/ui/overview.js
- js/ui/viewSelector.js
The current PR fixes the window picker animation by making it "symmetric" in that a zooming animation will now be shown both when entering and leaving the window picker. Additionally, this PR also include a couple of small fixes that are relate to this in that it makes the whole experience handling windows entering & leaving the overview better, not necessarily when interacting the window picker, but in general (e.g. when starting up).
https://phabricator.endlessm.com/T18032
> Fix the window picker animation

- js/ui/windowManager.js
Restore this nice animation by adding an extra check to determine
when the animation should be done, and adapt a bit the math so that
we don't see a strange effect when restoring the window back to its
place (currently, the window would shift to the left on finish).
https://phabricator.endlessm.com/T19761
> windowManager: Restore unminimize window animations

- js/ui/shellEntry.js
The OverviewEntry class tries to watch all the events
when it gets mapped, so that it can properly quit search
if the user clicks outside of the search entry and the
results page.
Checking if the entry is mapped or not, however, might
not be the optimal solution, for the entry can potentially
get mapped because of the grid clone, in which case it
ends up watching all the events without being at the
overview.
This has various side effects, the most noticeable being
the many missing clicks all around GNOME Shell. The other
noticeable issue is that some notifications are dismissed
even when their action buttons are clicked. This is 100%
reproducible with the Bluetooth panel.
Fix that by not only checking if the entry is mapped, but
also checking if the overview actor is visible too. …
> shellEntry: Also check for overview visibility

- js/ui/slider.js
The actor allocation will be invalid on CLUTTER_TOUCH_BEGIN, because
it comes together with a CLUTTER_ENTER event that will recalculate
styles, and queue a relayout in result.
The net result is that on CLUTTER_TOUCH_BEGIN, the relayout has been
already queued, so the slider width comes up as 0, and the value ends
up as 1. Later touch events already happen on a validated actor, so
it is corrected. Still, not fun when modifying the volume slider on a
touchscreen.
https://phabricator.endlessm.com/T18692
> slider: Cache slider width for dragging handlers

- js/ui/layout.js
- js/ui/overview.js
- js/ui/viewSelector.js
The fact that we want to start up directly in the Overview mode
on Endless combined with the possibility of having lots of icons
on the desktop makes it necessary to handle the first time the
overview is shown in a particular way in order to make it less
prone to flickering and confusion (e.g. already running apps
disappearing when restarting the shell).
However, we can't check the value of the startingUp property
from the layout because by the time Overview::show() gets called
the layout manager is no longer "starting up". Thus, add an
additional property to the overview so that we can do an extra
check to see if it's the first time it's shown, when needed.
This should be squashed with 4d34e93d in future rebases.
https://phabricator.endlessm.com/T19778
> overview, viewSelector: Handle first time the overview is shown

- data/theme/gnome-shell.css
This button was newly introduced with GNOME Shell, and the upstream
style doesn't play well with our style modifications to the background
of the menu, so replace it with a solid 1px border of the same colour
than other lines in the menu, to make it clear to the user that there
is a button in there.
https://phabricator.endlessm.com/T19807
> css: Re-style the "Clear All" button in the calendar popup menu

- data/theme/gnome-shell.css
- src/st/st-entry.c
Also, cherry pick a fix from upstream to avoid a crash when getting the text of a StEntry where no hint actor has been previously defined.
https://phabricator.endlessm.com/T19575
> Don't use a text-shadow on folder names when in editing mode

- js/ui/runDialog.js
This change makes it more convenient for developers to use Alt-F2,
without any impact to the normal user behavior.
[endlessm/eos-shell#555]
https://phabricator.endlessm.com/T19585
> runDialog: hide overview when launching command/document

- js/ui/remoteSearch.js
The apps word of the day and quote of the day do
provide a search provider. We want those to be
excluded from the search.
https://phabricator.endlessm.com/T19013
> RenmoteSearch: exclude content from evergreen apps

- js/ui/viewSelector.js
We're always starting up to the APPS page, and making the workspacesDisplay
visible when starting up would cause its actor to intercept Clutter 'picks'
intended for the grid unless it gets hidden first.
Since we're not interested in showing the Window picker on start up, just
avoid showing the workspacesDisplay actor when starting up to prevent this.
https://phabricator.endlessm.com/T19869
> viewSelector: Don't show the workspacesDisplay actor when starting up

- js/ui/appDisplay.js
In Endless, we have the apps grid (or a clone of it) showing up
all the time, so we can't defer updating it until the grid's actor
is mapped because that would create an artificial delay between an
icon gets added to the grid and the moment is made visible if the
"real" grid (not the clone) is not visible at that moment.
We still need to defer the call to redisplay() when starting up,
though, so that we don't draw anything until the grid is mapped.
https://phabricator.endlessm.com/T19596
> appDisplay: Only defer redisplay of the icon grid on startup

- js/ui/appDisplay.js
This broke folders management in that the event blocker won't work
correctly after having dragged and dropped an icon inside a folder,
preventing further open folders from being correctly dismissed.
This reverts commit e25680b16b6f941c8d79b48cd70f6b0c8793619b.
https://phabricator.endlessm.com/T19982
> Revert "appDisplay: Only defer redisplay of the icon grid on startup"

- js/gdm/authPrompt.js
- js/misc/keyboardManager.js
- js/ui/components/networkAgent.js
- js/ui/components/polkitAgent.js
- js/ui/shellMountOperation.js
- js/ui/status/keyboard.js
- src/shell-util.c
- src/shell-util.h
This adds the infrastructure to verify that the current
keyboard layout in use is a latin one when the user is prompted
to enter a password. The code to determine if a keyboard
layout is a latin is using the function "find_latin_keysym"
borrowed from Mutter.
In the near future we will switch automatically to an available
latin layout. If no suitable layout is available we
fallback to the default layout 'en'. The change is reflected in
the layout switcher in the taskbar.
When the password entry is in a modal dialog and the keyboard
switcher in the taskbar can not be accessed, we add another
switcher in the dialog, next to the password entry. The changes
made using this switcher are propagated to the keyboard
switcher in the taskbar and the popover menu revealed by the
super+space …
> passwordMode: add keyboard layout switcher for password entries

- configure.ac
Otherwise we will fail when linking the binary.
> build: add xkbcommon to shared dependencies

- js/ui/search.js
Otherwise, a shell restart will be required after installing a new
application, before its results can be seen in search.
https://phabricator.endlessm.com/T20057
> search: reload search providers when installed applications change

- js/ui/appActivation.js
This was already being checked when activating and app over the
org.gnome.Shell.AppLauncher D-Bus interface, but surprisingly
enough not when activating an app from the search results.
To fix this and make it less error prone, incorporate the check
into _shouldShowSplash(), and remove it from anywhere else.
https://phabricator.endlessm.com/T20114
> Don't show the splash screen for an app that's already running

- js/ui/status/keyboard.js
This makes the passwordMode feature available outside of the shell and can be used from gnome-initial-setup and gnome-control-center to check if a kbd layout is latin and add the fallback layout accordingly.
https://phabricator.endlessm.com/T18598
> passwordMode, InputSourceManager: expose Enabled property over D-Bus

- js/ui/appDisplay.js
This brings back the nice "bounce" animation we had in the old version
of the shell, that is run whenever a new icon is added to the icon
grid (e.g. Added to desktop from the App Center).
PS: Note that this PR goes against T18012 instead of master, as it depends on it to work.
https://phabricator.endlessm.com/T20087
> appDisplay: Add a scale-in animation when adding new icons to the grid

- js/ui/backgroundMenu.js
Otherwise it's possible to launch the App Center from it and,
with some additional effort, ending up executing anything even
before the FBE is finished.
https://phabricator.endlessm.com/T20471
> Disable the background menu when in initial-setup mode

- data/theme/gnome-shell.css
- js/ui/appDisplay.js
- js/ui/dnd.js
- js/ui/iconGrid.js
- js/ui/workspace.js
- js/ui/workspaceSwitcherPopup.js
- src/shell-app.c
- src/shell-app.h
Rebase of the previous work started in this branch in August, incorporating the changes done by @GeorgesStavracas in https://github.com/endlessm/gnome-shell/pull/165 and (hopefully) finishing it by simplifying it and fixing all the issues observed in that PR.
Main changes with regard to https://github.com/endlessm/gnome-shell/pull/165:
* Removed the animations performed when "reshuffling" icons on the desktop, as a result of DnD. Those animations were still pretty confusing as implemented in the previous PR (source of the animation did not match where the icon was being dropped from), and on top of that were inconsistent since no animations were shown when DnD'ing inside folders, so I'll file a new ticket for those and keep them out of this one, which should be focused on re-enabling DnD …
> Bring back DnD operations inside folders

- js/ui/discoveryFeedButton.js
There were occasions when a BUTTON_PRESS event was triggered when closing the DiscoveryFeed window by clicking on the Desktop.
https://phabricator.endlessm.com/T20602
> DiscoveryFeed: listen to clicked signal to reveal the window

- js/ui/panelMenu.js
The current code only qualifies the first button (usually
the left mouse button) as the qualifier for setting the
'clicked' pseudo class, when in fact all the three buttons
can trigger the popup menu.
Fix that by setting the clicked state on more buttons.
Should be squashed to 603c34c350c5 next rebase.
https://phabricator.endlessm.com/T20327
> panelMenu: Set the clicked state on more modifiers

- src/shell-app-system.c
If a window opens for which the Shell can't find an app ID, Shell logs
the following message to the journal:
Jan 05 18:09:11 endless gnome-shell[3003]: g_variant_new_string: assertion 'string != NULL' failed
This is because g_variant_new ("s", NULL) ultimately calls
g_variant_new_string (NULL) which is illegal. The
SHELL_APP_STATE_STOPPED branch has this NULL check, but it was missing
in the SHELL_APP_STATE_RUNNING branch.
While we are here, let's call g_variant_new_string() directly.
> fixup! shell-app-system: Report an event when an application opens/closes

- js/ui/appActivation.js
Otherwise, the callback will be called for any running app that
has ever shown the Speedwagon window, forcing them to close if
another Speedwagon window shown afterwards is manually closed.
https://phabricator.endlessm.com/T20699
> appActivation: Disconnect from the SplashClosed D-Bus signal

- js/ui/appActivation.js
- src/shell-app.c
Stop relying on the SplashClosed D-Bus signal from speedwagon, which causes race conditions we'd need to deal with since such signal arrives normally after the application being launched moves to a STOPPED state, as per the speedwagon's window being explicitly closed.
Instead, rely on the new logic implemented now in shell-app.c, which will detect when the speedwagon window has been explicitly closed and wait until the app would reach the RUNNING state to kill it by using the meta_window_delete() function once the app's window is mapped.
https://phabricator.endlessm.com/T20725
> shell-app: Make sure an app gets closed after closing its splash screen

- js/ui/remoteSearch.js
The search order properly put prioritized apps first, then apps
that are on the desktop, and finally apps that are installed
but not on the desktop.  The apps not on the desktop
were properly sorted alphabetically, but the apps that are on
the desktop were not sorted alphabetically with the old logic.
https://phabricator.endlessm.com/T15929
> remoteSearch: fix search order for apps on desktop

- data/theme/gnome-shell-sass/_endless.scss
I'm not sure how this could have worked before, but now we're using
SASS it's very clear that we need to swap the left/right paddings
used by default (0/12) when in RTL languages.
This should be squashed along with ee3f4f070d in future rebases.
https://phabricator.endlessm.com/T21235
> search: Fix style of the round search icon in RTL languages

- js/ui/components/trayArea.js
Also, rename ICON_SATURATION into ICON_DESATURATION, since that's what
the values are really about (and otherwise it's confusing).
https://phabricator.endlessm.com/T21427
> trayArea: De-emphasize icons, matching the style of system indicators

- js/ui/components/trayArea.js
This is another attempt to de-emphasize the icons in the tray area
so that they look better integrated with the system indicators.
https://phabricator.endlessm.com/T21427
> trayArea: Change the icon size to 16x16 pixels

- data/theme/gnome-shell-sass/_endless.scss
- js/gdm/loginDialog.js
For each item in the users list there is a vertical box packing exactly
an horizontal box with the user's avatar and name, and a small StBin for
the progress bar used for timed logins. The problem is that this second
actor is always taking up 2px of vertical space regardless of whether such
progress bar is visible or not, causing a permanent vertical misalignment
for the rest of cases, which happen to be the most common.
Fix this, by making sure that the 2px height and margin allocated for that
progress bar is only assigned when actually showing it, not always.
https://phabricator.endlessm.com/T21694
> loginDialog: Fix vertical misalignment of items in the users list

- js/gdm/loginDialog.js
- js/ui/screenShield.js
- js/ui/sessionMode.js
This integrates the PAYG unlock dialog in the login screen, making sure that such dialog is shown on boot & logout when the machine is locked.
https://phabricator.endlessm.com/T21609
> payg: Integrate the PAYG unlock dialog with the login screen

- js/ui/paygUnlockDialog.js
The 'Unknown error' message would cover this, but I think it's
interesting in this case to show something else for debugging
purposes, since an user pointing to us that a time out happened
will immediately direct us into a D-Bus communication issue.
https://phabricator.endlessm.com/T21806
> payg: Show an explicit error message when timing out

- js/misc/paygManager.js
This will prevent the daemon for running at all, since the Shell
will no longer need it to check whether PAYG is enabled in a machine.
https://phabricator.endlessm.com/T21844
> payg: Don't start the eos-paygd daemon if PAYG is not enabled

- data/theme/gnome-shell.css
- js/gdm/loginDialog.js
- js/js-resources.gresource.xml
- js/misc/paygManager.js
- js/ui/main.js
- js/ui/paygUnlockDialog.js
- js/ui/screenShield.js
- js/ui/sessionMode.js
- po/POTFILES.in
- src/st/st-entry.c
- src/st/st-private.c
This PR brings all the bits developed for the following tickets, onto the eos3.3 branch:
* Shell: Implement component to wrap the functionality of the eos-payg daemon (T21607)
* Shell: Add mechanism to unlock machine from the lock-screen session mode (T21608)
* Shell: Add screen to unlock machine from the GDM session mode (T21609)
* Shell: Automatically lock the user's session when a PAYG code expires (T21611)
* Shell: Add a timeout to the code verification process (T21806)
* Shell: Gracefully handle com.endlessm.Payg1.Error.TooManyAttempts (T21808)
* Shell: Implement design for the PAYG unlock dialog (T21811)
* Shell: Integrate PAYG with the FBE (T21830)
* Shell: Use the right text strings for the PAYG unlock dialog (T21841)
* Shell: Don't unnecessarily start the eos-paygd daemon …
> Backport the PAYG implementation into EOS 3.3

- js/ui/layout.js
It doesn't make sense to animate the clone if it hasn't been created
yet, which is something that can sometimes happen during startup, leading
to useless and confusing warnings on the journal.
This should be squashed with commit cb01f13f in future rebases.
https://phabricator.endlessm.com/T21739
> layout: Null-check for this._viewsClone in case it's not ready yet.

- js/ui/iconGridLayout.js
For some reason, we've been passing extra null parameters to this
function since forever, and keeping those wrong bits in past rebases.
This should be squashed along with 41cc7c26ef in future rebases.
https://phabricator.endlessm.com/T21738
> iconGridLayout: Pass the right parameters to Gio.File.load_contents()

- js/ui/status/network.js
Similar to what it's done when the main connection changes, we need
to make sure that the icon in the panel gets updated before calling
_syncConnectivity(), so that the icon gets always updated if needed,
regardless of whether there's an active connetion or not.
This is needed because there's at least one case when an icon should
be shown with the computer is not connected to any network: when a
hotspot has been enabled, which can be useful even if there's not
an internet connection to share (e.g. to easily allow connecting
other devices to the computer.
Closes: https://gitlab.gnome.org/GNOME/gnome-shell/issues/214
https://phabricator.endlessm.com/T22041
> network: Update the icon in the panel whenever NM's state changes

- data/theme/gnome-shell-sass/_endless.scss
https://phabricator.endlessm.com/T22226
> Fix icons misalignment and two-line labels in a11y's Large Text mode

- js/ui/notificationDaemon.js
This was the change I always wanted to propose in the previous PR,
but for some reason the updated branch didn't left my laptop and
never made it to github. Sorry about that.
https://phabricator.endlessm.com/T22100
> fixup! messageTray: Hide the overview when activating notifications

- js/ui/status/automaticUpdates.js
A minor issue with the JavaScript format string was found.
It does not affect functionality, but we better save the
correct value.
> fixup! Introduce Automatic Updates indicator

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/components/networkAgent.js
- js/ui/dialog.js
Per new design direction, we want the dialog labels to be centered
and use the High-Contrast toggle asset instead of the on|off switcher.
https://phabricator.endlessm.com/T22420
> fixup! networkAgent: Add switch button for metered connections

- js/ui/appIconBar.js
ClutterContainer.add() is patched in js/ui/environment.js to allow passing
child properties. We use ClutterActor.add_child() though, which doesn't
allow that, and causes warnings on the terminal when that code is
reached.
https://phabricator.endlessm.com/T21741
> appIconBar: use the right method to specify packing properties

- js/ui/components/discoveryFeed.js
- js/ui/windowManager.js
The discovery feed window animates in and out and the overview is
only shown once the discovery feed window is fully hidden (if the
overview was showing before). The Discovery Feed needs to know
when its window is fully hidden, since then it can launch the
relevant app (which will ensure that the overview is not shown
part-way through a speedwagon window being shown).
https://phabricator.endlessm.com/T22448
> discoveryFeed: Tell the Discovery Feed when its window is fully hidden

- js/ui/components/discoveryFeed.js
We removed the "timestamp" argument to callHide, but this
was unintentional.
https://phabricator.endlessm.com/T22448
> discoveryFeed: Revert accidental change to callHide

- src/wobbly-effect.c
Since the model is computed from the actor only paint box which
will be in the [0, model_geometry] space, this doesn't include
the top and left shadow offsets, so we need to apply them after
the fact. This corrects the computed paint volume so that there are
no shadow artifacts.
https://phabricator.endlessm.com/T23039
> wobbly: Use the paint box offsets to compute the right paint volume

- js/ui/boxpointer.js
- js/ui/dash.js
- js/ui/dialog.js
- js/ui/panel.js
Flag some actors that are good candidates for caching in texture memory
(what Clutter calls "offscreen redirect"), thereby mostly eliminating
their repaint overhead.
This isn't exactly groundbreaking, it's how you're meant to use
OpenGL in the first place. But the difficulty is in the design of
Clutter which has some peculiarities making universal caching
inefficient at the moment:
* Repainting an offscreen actor is measurably slower than repainting
the same actor if it was uncached. But only by less than 100%,
so if an actor can avoid changing every frame then caching is usually
more efficient over that timeframe.
* The cached painting from a container typically includes its children,
so you can't cache containers whose children are usually animating at
full frame rate. That results in a …
> js/ui: Choose some actors to cache on the GPU

- js/ui/windowManager.js
- src/wobbly-effect.c
Implementation of AnimationsDbus for the shell. 
We create an AnimationsDbusServer and register an
AnimationsDbusServerSurfaceBridge for each actor that can be
animated by the library, both at startup and also when actors
are mapped and unmapped.
The wobbly effect now has a "metaclass" to control its settings on a per-attachment basis (attaching the wobbly effect through GSettings represents a single attached effect instance on all windows, separate configurations of the effect can also be attached to other windows through the protocol).
https://phabricator.endlessm.com/T23314
> T23314: Prototype implementation of AnimationsDbus in GNOME-Shell

- src/shell-app-system.c
Tested as follows:
* Installed Pidgin from Flathub (it has `X-Flatpak-RenamedFrom=pidgin.desktop;`)
* Manually edited the `icon-grid-layout` property to replace `org.libreoffice.LibreOffice-writer.desktop` with `libreoffice-writer.desktop` (this has `X-Endless-Alias`) and `im.pidgin.Pidgin.desktop` with `pidgin.desktop`
* Restarted the unmodified shell: Writer was still shown on the desktop but Pidgin disappeared
* Started the modified shell: both were shown on the desktop
https://phabricator.endlessm.com/T22596
> shell-app-system: obey X-Flatpak-RenamedFrom

- js/ui/switchMonitor.js
In GNOME-3.24, pressing Super+P or a similar function key would cause
a switch to the next available monitor configuration.
However, in GNOME-3.26, this was reimplemented in mutter and gnome-shell
and the behaviour is now different: pressing Super+P and releasing will
cause no change in montor configuration[1]. In this new design you have
to press Super+P and keep holding Super in order to keep the switcher
open, then press P again (or use the arrow keys or mouse) to
select the next one in the list.
This is incompatible with many Asus products such as Asus X530UN, where
pressing the presentation mode media key (Fn+F8) actually generates
the following keypress events from the keyboard controller:
Fn pressed: nothing
F8 pressed: nothing
F8 released: Super press, p press, p release, Super …
> switchMonitor: switch to next config upon initial keypress

- js/ui/appFavorites.js
Previously, we handled renamed apps on the icon grid, but not on the
taskbar.
There is some clear overlap with the RENAMED_DESKTOP_IDS in this file,
which is inherited from upstream;
https://gitlab.gnome.org/GNOME/gnome-shell/issues/593 filed to discuss
upstreaming our approach.
Tested as follows:
* `gsettings set org.gnome.shell favorite-apps "['org.gnome.Software.desktop', 'google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'libreoffice-writer.desktop', 'pidgin.desktop']"`
* Restart the unmodified shell: neither LibreOffice nor Pidgin show on the taskbar
* Start the modified shell: both LibreOffice (X-Endless-Alias) and Pidgin (X-Flatpak-RenamedFrom) show on the taskbar
https://phabricator.endlessm.com/T22596
> appFavorites: respect X-Endless-Alias and X-Flatpak-RenamedFrom

- js/ui/appDisplay.js
The app center is special, since it's always pinned to the end of the grid
and is not part of the IconGridLayout.
The visible symptom of this is that searching for 'app' would rank other
apps (on my system, Steam, D-Feet and KeepAssXC, whose descriptions happen
to contain 'app') above the app center, which is correctly returned in the
highest-ranked group of results from g_desktop_app_info_search() since its
name matches the search.
I also noticed that this comparison function is poorly behaved; while that
wasn't the cause of this bug, it is worth fixing.
https://phabricator.endlessm.com/T23669
> Fix sorting App Center below other apps when searching for "app"

- src/shell-app-system.c
The original version of this code was incorrect. The third argument to
add_aliases() is a GDesktopAppInfo *, but shell_app_system_lookup_app()
passed the ShellApp * instead. (The compiler warns about this, but it's
not fatal and I missed it.)
This is presumably the cause of this repeated warning I spotted in the
journal:
g_desktop_app_info_get_string: assertion 'G_IS_DESKTOP_APP_INFO (info)' failed
https://phabricator.endlessm.com/T22596
> fixup! shell-app-system: refactor duplicated X-Endless-Alias code

- js/ui/appFavorites.js
- js/ui/endSessionDialog.js
- js/ui/workspacesView.js
The first patch fixes a regression introduced in #299. My (weak) claim is that I missed it in testing because the shell routinely prints warnings, including during startup where the bug would be triggered; as penance, I fixed a few "undefined property" warnings upstream and cherry-picked the fixes here as the middle 2 patches.
https://phabricator.endlessm.com/T22596
> Fix unbounded recursion bug & some unrelated warnings

- js/ui/appDisplay.js
- js/ui/appIconBar.js
- src/shell-app-system.c
- src/shell-app-system.h
eos3.4 version of #302. This is the code I tested in situ on a machine running eos3.4. The differences are in these two patches:
* appIconBar: react to external changes to favorites
* appIconBar: remove redundant lookup
On master, Shell.GenericContainer has been removed; on eos3.4, `.actor` is needed in a few places to get from the JS-land object to the Clutter actor. Here's the diff between the two pairs of changed patches: https://gist.github.com/wjt/e8d41854e9492f19fd2fa6f3cda093e1
https://phabricator.endlessm.com/T23877
> Improve .desktop file change detection (eos3.4 version)

- js/ui/appDisplay.js
- js/ui/appIconBar.js
- src/shell-app-system.c
- src/shell-app-system.h
Superset of #303 with a fix for this bug:
* Foo is on the desktop; `org.foo.Foo.desktop` contains the line `Exec=zenity --info --text Foo`
* During the session, the user (or automatic updates) installs an update for Foo; `org.foo.Foo.desktop` now contains the line `Exec=zenity --info --text FooBar`
* User clicks the Foo icon on the desktop; the old `Exec=` line is still used
In practice, this bug manifests itself when migrating from the KDE 4 version of ktuberling in eos-apps (which uses `-caption %c` in its desktop file) to the KDE 5 version on Flathub (which uses `-qwindowtitle %c`). The `-caption` syntax is not supported by the Flathub version; as a result, the app can't be launched from the desktop 
**TODO**:
https://phabricator.endlessm.com/T23877
> Improve .desktop file change detection

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/codeView.js
- js/ui/windowManager.js
- src/shell-window-tracker.c
- src/shell-window-tracker.h
This is a preliminary PR for the current implementation of flip to hack, generalizing what was already in place to flip between GNOME Weather and Builder. We now have the concept of a "toolbox" which sits on the other side of a hackable window. 
The canonical implementation of toolboxes for the apps we care about so far is developed in https://github.com/endlessm/hack-toolbox-app
It has a couple of known issues:
- There's an odd behavior when the toolbox is minimized; the window behind it is also minimized but it becomes transparent. 
- The animation probably needs to flip back when the toolbox is closed directly.
And a few FIXMEs in the code where things need to become more generic. However, this is ready for a round of review, as it's a sizable branch. I split the work in many commits …
> Flip To Hack

- js/ui/windowManager.js
We have a second code path to account for windows mapped while the
speedwagon is up. Make sure CodeViewManager handles that case too.
https://phabricator.endlessm.com/T24057
> windowManager: let codeview handle windows while speedwagon is up

- js/ui/codeView.js
Now that we have a default lockscreen implementation, we can remove
any special case from the shell.
All applications are going to have a FlipToHack button, and those
without a more specialized implementation, are going to get a
lockscreen by default.
https://phabricator.endlessm.com/T24015
> codeView: enable for all applications

- js/ui/components/clubhouse.js
The Clubhouse may choose to withdraw a notification (in order to stop
the Shell Quest View) without having the quest being stopped (so it may
keep showing the quest inside its window).
To accomplish that, this patch checks what's the reason for closing the
notification, and doesn't dismiss the quest if the reason is "source
closed".
https://phabricator.endlessm.com/T24105
> clubhouse: Don't stop a quest when the notification is withdrawn

- data/theme/gnome-shell-sass/_endless.scss
- js/misc/paygManager.js
- js/ui/paygUnlockDialog.js
There are four parts to this:
* Always ask the daemon if it's enabled, rather than reading its config file (https://github.com/endlessm/eos-payg/pull/24 teaches the daemon to time out after 30 seconds if PAYG is disabled, and in any case its resource usage is minimal)
* Pick up the CodeFormat property introduced in https://github.com/endlessm/eos-payg/pull/24
* Rework code validation to use that property, rather than assuming all codes must be 8 digits
* Adjust the CSS a bit so that the longer codes used by the provider plugin at https://github.com/endlessm/eos-payg-nonfree/pull/1 fit in the available space
https://phabricator.endlessm.com/T23965
> Support alternative PAYG code formats

- js/ui/status/power.js
The pending-charge state means AC power is on but the battery is not
being charged because its charge is above a certain threshold, to avoid
short charing cycles and prolong the battery's life. From the user's
perspective this is equivalent to the situation where the battery is
fully charged.
This commit sets the power indicator label for the pending-charge state
to "Fully Charged".
https://phabricator.endlessm.com/T24044
> power: Label the PENDING_CHARGING state as Fully Charged

- js/ui/shellDBus.js
Calling the ShowApplications() method was displaying the app windows
view instead of the app grid.
https://phabricator.endlessm.com/T24218
> shellDBus: Fix showing the app grid

- js/ui/codeView.js
This will take precedence over NoDisplay=true to determine whether the
app should be considered hackable or not (e.g. HackUnlock has
NoDisplay=true, but we want it to be considered hackable.)
https://phabricator.endlessm.com/T23942
> codeView: support X-Endless-Hackable custom desktop key

- js/ui/windowManager.js
Avoid the destroy animation code path, since there are many cases
when that callback returns early (e.g. when the overview is visible),
which will still lead to an unbounded array of animatable surfaces
left behind.
The 'unmanaged' signal is emitted by Mutter when a MetaWindow is
destroyed, so this commit uses that instead.
https://phabricator.endlessm.com/T24192
> windowManager: use unmanaged signal to unregister animations

- js/ui/codeView.js
In particular, we are interested right now in supporting a 'none' type
for apps such as HackUnlock for which we want no shader.
In the future, this can be extended to have different apps choose
different shader types.
https://phabricator.endlessm.com/T24241
> codeView: support different shader types

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/components/clubhouse.js
Add a new signal PulsingIcon in the D-Bus interface. When triggered,
the icon of the Open button is styled with a "highlighted" class.
When the Open button is clicked, the "highlighted" class is removed.
The pulsing animation is done in the CSS by transforming two images in
loop.
The clubhouse-icon-highlighted.png image is a placeholder made by
coloring the icon for the normal state.
https://phabricator.endlessm.com/T24164
> clubhouse: Pulse the "open" button to indicate the user to click it

- js/ui/components/clubhouse.js
Which is every session but the user one.
In particular, this will hide the button on the initial-setup session.
https://phabricator.endlessm.com/T24404
> clubhouse: hide button for sessions that do not have an overview

- js/ui/components/clubhouse.js
We need to make sure that the text displayed in the quest view banner
is split to fit in the expected UI (because some quest messages have a
long text to be displayed).
Even though we may need a more advanced technique to make this text
split, for now we're just splitting the text in parapraphs.
To advance through the text, we include a "next page" button, and only
add any eventual notification actions when the last page is displayed.
https://phabricator.endlessm.com/T24219
> clubhouse: Paginate text by paragraph in the quest view banner

- js/ui/components/clubhouse.js
The pages can only be set if we're in the last page of the dialog, but
we were relying on the banner's parent to set them in the constructor
too, and this was never happening because the page index was only
updated after the parent's contructor.
This patch fixes that by setting the right page index before the
parent's constructor.
https://phabricator.endlessm.com/T24219
> clubhouse: Fix setting the actions in the banner

- src/st/st-texture-cache.c
StTextureCache installs file monitors that invalidate caches when
contents of the underlying file change.
At the moment, the cache uses the Gio.FileMonitorEvent.CHANGED event
type to make that determination.
However, that is suboptimal for at least two reasons:
- while a file is being written to disk, many CHANGED events will be
emitted in sequence. That will cause needless cache invalidations,
and we will risk loading the file before it's fully loaded.
- if an existing file is replaced, e.g. with g_file_replace(), we may
not get a CHANGED event but a CREATED one instead, so the cache ends
up never getting invalidated.
The good news is that in both of those cases GFileMonitor will send a
CHANGES_DONE_HINT event after changes have settled, or after the file
is replaced.
This commit fixes …
> StTextureCache: use right event to detect file changes

- js/ui/status/power.js
The pending-charge state means AC power is on but the battery is not
being charged. This can happen because its charge is above a certain
threshold, to avoid short charging cycles and prolong the battery's
life, or because the PSU is not powerful enough to charge the batteries.
Instead of lying to the user about something being estimated, we should
simply tell the truth and set the label to "Not Charging".
https://phabricator.endlessm.com/T24044
>  power: Label the PENDING_CHARGE state as "Not Charging"

- src/shell-code-view-effect.c
Our gradient map algorithm does not work well on areas with an alpha
channel; in particular, we are interested in excluding the invisible
borders around the window from the shader.
This commit disables the shader where an alpha channel is in use in
the app window.
https://phabricator.endlessm.com/T24193
> ShellCodeViewEffect: ignore alpha areas for shader

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/codeView.js
This does not actually change the position of the button, but at the
moment we set a large left padding, which makes it so  the button is
clickable for a large portion immediately left of the window.
Instead, position it flush on the window edge, and add a small left
padding.
https://phabricator.endlessm.com/T24407
> codeView: improve placement of FlipToHack button

- js/ui/components/clubhouse.js
The first quest (HackUnlock) shouldn't have a close button (because the
Clubhouse is not supposed to be used while in that moment). Thus, this
patch only allows the close button in quest banners to be visible if the
session has an overview (i.e. if changing windows is a normal thing).
This is not a very flexible way of changing the close button's
visibility, but it is not clear ATM whether we will need something much
more clever to justify the extra time involved in that.
https://phabricator.endlessm.com/T24405
> clubhouse: Change the visibility of the close button in quest banners

- js/ui/components/clubhouse.js
This boolean property replaces the previous signal. Removes disabling
the highlight when the clubhouse is open, because the remote
application now switches the property to false.
https://phabricator.endlessm.com/T24507
> clubhouse: Connect to changes in the SuggestingOpen D-Bus property

- js/misc/ibusManager.js
At the end of the first boot experience, the newly-created user is
signed in, and GDM tears down the gnome-initial-setup session by sending
SIGTERM to its gnome-session's process group. gnome-shell is a child of
gnome-session, and currently spawns ibus-daemon directly as a
subprocess.
However, one of the first actions ibus-daemon takes is to move itself to
a new process group, so it escapes the SIGTERM sent to gnome-session's
process group at the end of the session. Ordinarily, this wouldn't
matter, because the X11 session would soon also die, causing the
ibus-x11 process (spawned by ibus-daemon) to die; its last act is to
send a message to ibus-daemon, telling it to terminate. But in this case
we are reusing the X11 session for the new user, since on Endless GDM is
built with …
> ibus: launch daemon via D-Bus service activation

- js/ui/components/clubhouse.js
The banner is supposed to be always visible until the user eventually
dismisses it.
https://phabricator.endlessm.com/T24558
> clubhouse: Do not close the item banner after a timeout

- js/ui/components/clubhouse.js
When the Clubhouse window is opened, any banner who's been created with
the "shouldSlideIn" variable will also be slid in from the right again.
The reason is that we track the Clubhouse window and call for the
banners to be repositioned when the window appears (so they're
positioned to the left of it), which will use the slide in effect again.
To avoid this, this patch sets the mentioned variable to false after the
first time the banner is slid in. This is the desired behavior for all
banners in any case, fixes the mentioned issue.
https://phabricator.endlessm.com/T24599
> clubhouse: Only slide notification banners in once

- js/misc/parentalControlsManager.js
The logic for how to work out whether a particular Gio.AppInfo is
blacklisted has been moved into a new API in libeos-parental-controls;
so use that.
This introduces no functional changes.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T24017
> parentalControlsManager: Factor out ‘should show’ logic

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/components/clubhouse.js
To mimic the banner inside the clubhouse application.
Rearrange the three main elements of the banner: icon, content box,
and buttons box. In the superclass these elements are layed out inside
horizontal and vertical boxes of type St.BoxLayout. This commit
removes them from the boxes and adds them to a new wrapper widget. The
wrapper has a layout manager Clutter.BinLayout, so the elements are
arranged in layers.
Also update the CSS to make the banner as similar as possible to the
banner inside the clubhouse.
https://phabricator.endlessm.com/T24503
> clubhouse: Theme the notification banner

- js/ui/components/clubhouse.js
The item banner was calling the _addActions method directly in its
constructor, but due to some changes in the base class, this is no
longer needed and as a result, it'll end up adding the double of
actions/buttons to the banner.
https://phabricator.endlessm.com/T24625
> clubhouse: Don't add actions directly in the item banner

- js/ui/components/clubhouse.js
The Clubhouse notification source is getting destroyed when it runs out
of notifications, and it was calling the action to stop the ongoing
quest in the Clubhouse. This was a problem when stopping a quest from
the Clubhouse and immediately start another, because the Clubhouse
itself stops the ongoing quest (and removes the notification) which
would end up destroying the notification source and thus getting the
"stop quest" action called again, while at this point the new quest may
be running already.
i.e. the new quest would be quickly stopped because of the "stop quest"
action called by the Clubhouse notification source destruction.
This patch stops this behavior by not calling the mentioned action when
the Clubhouse notification source is destroyed. This was unnecessary
in any case, …
> clubhouse: Don't stop the quest if the notification source is destroyed

- js/ui/components/clubhouse.js
Instead of relying on this._clubhouseSource.
Both the clubhouse source and the clubhouse component connect to the
destroy signal of the notification; the clubhouse source callback will
destroy the source when there are no notifications, while the
clubhouse component will possibly activate the stop-quest action.
We set the source to NULL in the clubhouse component when it's
destroyed, but that happens before the other callback for the
stop-quest action to be activated is reached. Since the stop-quest
action is currently activated on the clubhouse source reference owned
by the clubhouse component, the result is that we never manage to
activate the action when the notification banner is destroyed.
This commit fixes the issue by using the source reference owned by the
notification in order to …
> clubhouse: use source from notification to activate action

- js/ui/screenShield.js
Even when the gnome-initial-setup has technically credentials, it's not
correct to show the "unlock-dialog" screen under any circumnstances.
https://phabricator.endlessm.com/T24114
> js: Don't show unlock-dialog during initial-setup

- js/ui/codeView.js
For reasons unclear, when a new notification banner appears during the
flip to hack animation, the button can get into a state where it stops
reacting to events.
Hiding and re-syncing its visibility again in that case fixes the
issue, so that's what this commit does.
As a small cleanup, we move restoring the button state to a separate
function as well, to separate it out from the animation logic.
https://phabricator.endlessm.com/T24788
> codeView: fix flip-to-hack button not being reactive

- data/theme/gnome-shell-sass/_endless.scss
The image size in the CSS was hardcoded and can be removed. This
change has no effect for images coming from the clubhouse with a size
equal or less of the hardcoded size. But for larger images, this
change will allow them to expand to the right.
https://phabricator.endlessm.com/T24917
> clubhouse: Remove CSS rule for notification image

- js/ui/components/clubhouse.js
When a banner is sliding in and the Clubhouse is hidden, the banner may
end up in the wrong position in the screen. This happens because, even
though we reassign the banner's X coordinate, the tweener may still be
actively changing it too.
To avoid that, this patch removes any tweens in the banner's actor if a
new position is to be assigned to it, and only changes the
"shouldSlideIn" variable at the end of the tween. This means that until
a first slide in is achieved, the banner cancels and starts a new slide
in animation if its target X coordinate changes.
This gets us the right effect of having the banner sliding in, even when
a new X coordinate is set in the middle of a slide.
https://phabricator.endlessm.com/T24691
> clubhouse: Fix banners' position when initially showing them

- js/ui/components/clubhouse.js
The new approach for closing the quest banner is that we don't stop the
quest, instead we simply inform the Clubhouse that the banner has been
closed.
https://phabricator.endlessm.com/T24641
> clubhouse: Don't stop quests when closing their banner

- js/ui/codeView.js
We must use frame coordinates here, since one of the windows may be
client-side decorated, and we don't want to constrain the other side
to a size including the shadows/borders, since the toolbox may be
server-side decorated.
This fixes a size mismatch between the toolbox and the application
windows for small applications such as the calculator.
https://phabricator.endlessm.com/T24656
> codeView: compare dimensions in frame coordinates for constraints

- js/ui/components/clubhouse.js
The Clubhouse side component was being shown by just calling a D-Bus
method on the app. However, this meant that the usual activation logic
for launching apps was not used, and thus there was no startup
notification for the user; i.e. no spinner cursor was being shown to the
user, indicating that the app is loading, which hindered the UX.
This patch fixes that issue by launching the app with the meantioned
activation logic. It however only does that if the app is not running
already, as a workaround for a common issue in the Shell: if the app is
already running, activating it again will show the spinner cursor for a
long time.
https://phabricator.endlessm.com/T24728
> clubhouse: Activate the app instead of using a D-Bus method

- js/misc/paygManager.js
- js/ui/payg.js
- src/shell-util.c
- src/shell-util.h
The "ExpiryTime" property of the EpgProvider interface is changing to be
in terms of CLOCK_BOOTTIME rather than wall clock time, this commit
changes the paygManager class to account for this.
https://phabricator.endlessm.com/T24300
> paygManager: Understand ExpiryTime in terms of CLOCK_BOOTTIME

- js/misc/paygManager.js
Add missing import for the Shell.util_get_boottime() function.
https://phabricator.endlessm.com/T24300
> payg: Add missing import

- js/ui/windowManager.js
At the moment, we only forward the window destroy event to
CodeViewManager when a determination is made that the window needs an
animation, and is a normal window.
However, whether the window needs an animation also depends on
external factors, such as whether the overview is visible. We don't
want to miss the even in those cases, or we can e.g. end up with a
mismatched app/toolbox pair when an app is closed while the overview
is visible.
This commit fixes that by simply passing the event over to
CodeViewManager earlier. If the event referred to a window that is not
tracked by CodeViewManager, no harm is done anyway.
https://phabricator.endlessm.com/T25040
> windowManager: always pass window destroy event to CodeViewManager

- js/ui/status/payg.js
Currently the payg tray applet only decrements the displayed number of
minutes remaining once and then stays stuck at a number (e.g. 58
minutes) until the credit expires completely. This is because we're not
returning GLib.SOURCE_CONTINUE in the callback, so fix this so that the
applet updates the time remaining every 60 seconds.
https://phabricator.endlessm.com/T24300
> payg: Properly update time remaining every minute

- js/ui/components/clubhouse.js
Since the Clubhouse Shell component caches the metadata for the
animations coming from the Clubhouse, there can be the case where, if
the Clubhouse is updated and it brings a different metadata for an
existing animation that's cached in the Shell, any attempt
to create the animation will use the right sprite file but the outdated
metadata, thus likely resulting in a crash (due to trying to
clip the sprite with the wrong values).
This patch fixes this issue by clearing the metadata cache every time
the Clubhouse is quit. This means that if there is an update to the
Clubhouse and it is relaunched, there will be no cached metadata for
animations at that point, thus preventing the issue mentioned above.
https://phabricator.endlessm.com/T25118
> clubhouse: Clear animations metadata cache when the Clubhouse is quit

- js/ui/components/polkitAgent.js
- js/ui/search.js
- js/ui/status/keyboard.js
This is a tentative fix for the residual polkit dialogue seen on some OpenQA test runs, such as https://openqa.endlessm.com/tests/12952#step/desktop_travel/23. That polkit dialogue should have been cancelled by polkitd, as can be seen from the journal for that test run:
```
Jan 18 11:20:30 endless polkitd[367]: Operator of unix-session:2 FAILED to authenticate to gain authorization for action org.freedesktop.Flatpak.runtime-install for system-bus-name::1.249 [/usr/bin/gnome-software --gapplication-service] (owned by unix-user:test)
Jan 18 11:20:30 endless gnome-software[1612]: failed to call gs_plugin_app_install on flatpak: failed to get permissions: Unable to load metadata from remote eos-apps: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Flatpak system operation Deploy not …
```
> T24855 Fix polkit dialogue signal handling

- js/ui/components/clubhouse.js
This PR fixes the button positioning with multiples monitors. I've tried adding an external monitor to the right, top, left and bottom and it works okay in all the cases.
To do this I've changed the button, instead of drawing the complete circle 110x110 and positioned at the edge of the screen, I've changed that to draw it 55x110 so there's no part of it in the secondary monitor.
The second commit fixes the button positioning when we've the external monitor above or below the primary.
https://phabricator.endlessm.com/T25241
> T25241 clubhouse button ext monitor

- js/ui/codeView.js
To avoid the codeview button to be placed above the bottom panel and
other floating dialogs like the shutdown dialog, I moved the actor below
the panelBox.
https://phabricator.endlessm.com/T24683
https://phabricator.endlessm.com/T25061
> codeview: Place the button below the panel box

- js/ui/windowManager.js
When we've multiple monitors and the workarea is expanded, we can view
the animation for the side components in the external monitor during the
slide.
To avoid this, this patch adds a callback for each Tweener animation to
clip the actor during the update. Doing this, the actor isn't visible in
the other monitors.
This problem was detected as part of the https://github.com/endlessm/gnome-shell/pull/430, so it's related with this task: https://phabricator.endlessm.com/T25241
> sideComponent: Clip side components during slide

- js/ui/codeView.js
The toolbox is being lazy loaded when the user clicks the FtH button. If
the toolbox is a bit complex, this loading can take some time and the
feedback for the user is odd because the interface freezes after the
click.
To try to *improve* the flipping time, we can preload the hack toolbox
for the app before the user clicks the FtH. This patch calls to the init
method of the HackToolbox, when the button is shown only if it's not
init yet.
This depends on this change for the hack toolbox:
https://github.com/endlessm/hack-toolbox-app/pull/130
if the hack toolbox app doesn't have this action yet, the preload won't
work and the FtH will continue working as usual.
https://phabricator.endlessm.com/T25093
> codeView: Preload toolbox before the flip

- js/misc/paygManager.js
- js/ui/payg.js
Pay-As-You-Go Notifications keep appearing after being
useful when using eos-payg-ctl in the middle of a
time-session or when the session expires normally. So we
clean all notifications on the message tray when a
expiry-time-changed signal is sent.
https://phabricator.endlessm.com/T25246
> config: Remove obsolete notifications

- js/ui/messageList.js
When the message gets expanded, the URLHighlighter is instantiated
again. So simpleMarkup should be passed to the constructor.
https://phabricator.endlessm.com/T25192
> messageList: Fix specifying simple text markup in message body

- js/ui/payg.js
Local method is not being found without the <this>
identifier, so we use it.
https://phabricator.endlessm.com/T25246
> fix: Remove obsolete notifications

- js/ui/payg.js
When adding more that 10 codes, the notification tray
should show a "Too many attempts. Try again in 30 minutes".
Instead, it only showed a spinner animation indefinetly, due
to a broken import.
https://phabricator.endlessm.com/T25132
> payg: Missing shell import

- js/ui/shellDBus.js
The AddApplication method uses this varaible as an identifier to record
this event. This variable should have been removed during the 3.32
rebase but the reference is there causing a crash on every call.
This patch recovers this line from previous commits.
> ShellDBus: Add SHELL_APP_ADDED_EVENT

- js/ui/appDisplay.js
this._views doesn't exists in the current version so we should remove
this reference because it's undefined.
> appDisplay: remove reference to this._views

- js/ui/components/clubhouse.js
If we install/uninstall a different version of the clubhouse and a new
clubhouse notification comes to the shell, the notification code will
not find the image because the flatpak path has changed.
This patch fixes that problem reloading the clubhouse flaptak
directories if we can't find the animation image. This will be only done
once to avoid an infinite recursion in the case of trying to find a non
existing image.
https://phabricator.endlessm.com/T26543
> clubhouse: Reload clubhouse paths on fail

- js/ui/appDisplay.js
This reverts commit 92f1aec3dd1a373645aa0f70016440993a8ac997. With
resource scale in place, this is not necessary anymore.
https://phabricator.endlessm.com/T26531
> Revert "appDisplay: Fix small app folder icons when using HIDPI"

- js/ui/components/clubhouse.js
The clubhouse notification parent class calls to _addActions before we
set the pagination and this is causing duplicates actions because then
we're adding the action again.
https://phabricator.endlessm.com/T26646
> clubhouse: Do not add actions twice during the init

- js/ui/appDisplay.js
- js/ui/iconGridLayout.js
Currently, if you right-click an app icon and click “Remove from
desktop”, you see a notification reading “$APP has been deleted”, which
is not true. If you drag an icon, the app center icon changes to a trash
can, and the label changes to “Delete”, which is inaccurate in the same
way.
Change these strings to say “remove[d]”, not “delete[d]”, per design
direction in March 2017(!).
https://phabricator.endlessm.com/T16267
> icon-grid: improve wording when removing desktop icons

- data/dbus-interfaces/meson.build
- data/dbus-interfaces/org.gnome.Shell.AppLauncher.xml
- data/eos-launch.desktop.in.in
- data/gnome-shell-dbus-interfaces.gresource.xml
- data/meson.build
- js/misc/eos-launch.js
- js/misc/meson.build
- js/ui/appActivation.js
- js/ui/shellDBus.js
Backport of #469 to eos3.6. The first patch did not apply cleanly due to 1e206133a not being on eos3.6, but the conflict seems easy enough to resolve.
https://phabricator.endlessm.com/T26726
> Reintroduce Shell API to launch applications (eos3.6)

- js/ui/windowManager.js
I spotted this while working on https://github.com/endlessm/gnome-shell/pull/475. It makes xgettext sad:
$ ninja -C obj-x86_64-linux-gnu/ meson-gnome-shell-update-po
ninja: Entering directory `obj-x86_64-linux-gnu/'
[0/1] Running external command gnome-shell-update-po.
xgettext: warning: file 'data/50-gnome-shell-system.xml' extension 'xml' is unknown; will try C
js/ui/windowManager.js:1146: warning: unterminated string
(The first warning is an upstream bug.)
As it happens, this problem has no effect on the generated .pot file, but I think it would prevent xgettext from seeing translatable strings later in the file.
https://phabricator.endlessm.com/T25388
> windowManager: don't use ES6 `template strings`

- src/st/st-texture-cache.c
We're storing in the texture cache images and scaled images appending
the scaling factor to the key. When a file changes the cache key
corresponding to that file is removed, but not the keys for the scaled
ones so that images in the cache are never reloaded.
This patch removes all keys from the cache related to the file that
changes, including those with the scaling factor.
https://phabricator.endlessm.com/T26505
> texture-cache: Remove also scaled keys from the cache

- js/ui/overview.js
When the lid is closed and opened again in a desktop without any app
opened, the overview is hidden and never get shown again. This causes a
desktop with disabled buttons.
To avoid this, this patch calls to showApps just after the hide but only
if the app buttons are visibiles before the hide call.
https://phabricator.endlessm.com/T24778
> overview: Show apps again after relayout

- js/ui/iconGridLayout.js
Passing an invalid JSON file may cause GNOME Shell
to have undefined behavior, due to the JSON loading
routines not being protected against broken files.
Fix that by wrapping the call in a try / catch.
https://phabricator.endlessm.com/T20843
> iconGridLayout: Protect against invalid JSON

- js/misc/parentalControlsManager.js
- meson.build
malcontent was released with the intention of upstreaming parental
controls work across the GNOME stack. As upstream efforts have already
started in various GNOME modules, we should also migrate to malcontent
so that our upstreaming efforts are aligned and future rebases become
a bit smoother.
This commit introduces no functional changes. It is just replacing
EosParentalControls with malcontent and is based off Philip Withnall's
initial upstream merge request [1].
[1] https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/465
https://phabricator.endlessm.com/T26997
>  js: Migrate parental controls backend to malcontent

- js/misc/parentalControlsManager.js
- js/ui/appDisplay.js
- js/ui/iconGridLayout.js
- js/ui/search.js
Hook up to "app-filter-changed" signal from malcontent and if the app
filter is changed for the currently logged in user, enforce the new
app filter in the shell. This is one of the main pieces for our feature work
in T26893.
https://phabricator.endlessm.com/T26969
> js: Make Shell responsive against app-fitler changes for current user

- data/theme/gnome-shell-sass/_endless.scss
- js/misc/paygManager.js
- js/ui/payg.js
- js/ui/paygUnlockDialog.js
Add a prefix and sufix characters for codes inserted on the
payg-unlock-screen, making it more user-friendly.
This is blocked on endlessm/eos-payg#44 and endlessm/eos-payg-nonfree#18
https://phabricator.endlessm.com/T25987
> eos-payg: Add prefix and sufix characters for code insert

- js/ui/shellDBus.js
All DBUS calls to this method raises a Timeout exception because the
launch method never returns anything to the invocation.
This patch fixes that problem returning null when the application is
activated.
https://phabricator.endlessm.com/T27234
> appActivation: Return value on launch invocation

- js/gdm/authPrompt.js
Relevant error message inside journal:
Jul 10 20:19:09 endless gnome-shell[662]: JS ERROR: ReferenceError: Gio is not defined
_maybeShowPasswordResetButton@resource:///org/gnome/shell/gdm/authPrompt.js:672:13
_onVerificationFailed@resource:///org/gnome/shell/gdm/authPrompt.js:306:16
_emit@resource:///org/gnome/gjs/modules/signals.js:142:27
_verificationFailed@resource:///org/gnome/shell/gdm/util.js:561:9
_onConversationStopped@resource:///org/gnome/shell/gdm/util.js:579:13
https://phabricator.endlessm.com/T27205
> fixup! passwordReset: Implement Endless-specific password reset feature

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/payg.js
https://phabricator.endlessm.com/T25988
This is blocked on the merge of https://github.com/endlessm/gnome-shell/pull/477
> eos-payg: Add prefix and suffix characters for the payg-tray

- js/ui/appDisplay.js
The hack icon is connected to the property hack-mode-enabled to change
when the hack mode is enabled or disabled. This should be disconnected
on destroy to avoid calling it when the icon is deallocated.
https://phabricator.endlessm.com/T27140
> Disconnect hack-mode-enabled property on hack icon destroy

- js/ui/appIconBar.js
Some notes on the changes:
- Apart from the parental controls support for taskbar favorite apps, these changes includes fixes for a couple issues that are also valid for 3.6:
- crash when pinning/unpinning app - see https://phabricator.endlessm.com/T27191#735008 for more details on how to reproduce
- the taskbar app icon highlight state sometimes would not get updated when the app was closed (i.e. the button would stay highlighted)
- If an app is blacklisted while already running the app will stay running and the taskbar button for it will stay visible in the taskbar until the app is closed
- The favorites positions are respected when disabling/enabling the apps via parental controls
https://phabricator.endlessm.com/T27191
https://phabricator.endlessm.com/T26981
> Add parental controls filtering to favorite apps/taskbar pins

- js/ui/appActivation.js
- js/ui/appIconBar.js
Changes include:
- Do not show splash/speedwagon if app is blacklisted
- Do not show taskbar button if app is starting and blacklisted
Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>
https://phabricator.endlessm.com/T26990
> Hide splash/taskbar button when app is starting/blacklisted

- js/ui/codeView.js
For the katamari Hack flatpak we've all needed components inside only
one flatpak, and we've there the Clubhouse and the HackUnlock apps. The
HackUnlock doesn't export the desktop file and for that window the shell
get the appInfo for the com.endlessm.Clubhouse.desktop, so we need to
check the gtk_application_id to differentiate between those two apps and
provide the corresponding toolbox.
The com.endlessm.HackToolbox is the same, we need to check the real id
because the appInfo is the one for the flatpak itself.
https://phabricator.endlessm.com/T27274
> codeView: Check gtk_application_id when it's present

- js/ui/workspace.js
Under some (unknown) circumstances, Shell.WindowTracker's
get_window_app() method may return NULL. The code under
workspace.js is not robust against that. This is reproducible
with Minetest.
Check for a NULL app, and return an empty title when that's
the case, before trying to retrieve the app title.
https://phabricator.endlessm.com/T27263
> workspace: Protect against NULL apps

- js/ui/codeView.js
If you've the hack mode enabled and you uninstall the clubhouse, the
hack-mode-enabled continue being true and in this case we should not
show the Flip to Hack button in any case.
https://phabricator.endlessm.com/T27420
GNOME rebase note:
This can be squashed with the following commit in the next shell rebase:
codeView: Add codeview to provide Flip to Hack (b5ad90504)
> codeView: Don't show FtH button when clubhouse isn't installed

- js/misc/soundServer.js
- js/ui/appDisplay.js
- js/ui/codeView.js
- js/ui/components/clubhouse.js
- src/shell-window-tracker.c
Rename hack services and apps to com.hack_computer instead of
com.endlessm, this is the new prefix that we'll use
https://phabricator.endlessm.com/T27400
> Hack2 deploy: rename hack apps

- js/ui/notificationDaemon.js
- src/shell-global.c
An Endless OS system was found in the wild with a malformed `.local/share/gnome-shell/notifications`. When deserialized in Python, after passing `trusted=True` to `g_variant_new_from_bytes()`, the first element of the first struct in the array looks like this:
In [41]: _38.get_child_value(0).get_child_value(0)
Out[41]: GLib.Variant('s',
'\Uffffffff\Uffffffff\Uffffffff\Uffffffff\Uffffffff')
When deserialised in GJS, we get:
gjs> v.get_child_value(0).get_child_value(0)
[object variant of type "s"]
gjs> v.get_child_value(0).get_child_value(0).get_string()
typein:43:1 malformed UTF-8 character sequence at offset 0
@typein:43:1
@<stdin>:1:34
This branch addresses this problem on two fronts:
* Pass `trusted=FALSE` to `g_variant_new_from_bytes()`, as recommended by `g_variant_new_from_data()`'s …
> Don't crash on startup if saved notification data is corrupt

- js/ui/codeView.js
- src/shell-window-tracker.c
Old hack apps with the com.endlessm.X ID uses the old HackToolbox that
has the id com.endlessm.HackToolbox. The new hack apps and distribution
are using the new ID prefix com.hack_computer. but we can keep backward
compatibility in the shell to avoid break current hack-computer
installations.
This patch uses one toolbox or another depending on the app ID. This is
one step forward to the posibility of different toolboxes apps for
different apps, but right now there's only these two that are the same
but old and new versions.
https://phabricator.endlessm.com/T27673
> codeView: Use old or new HackToolbox depending on ID

- js/ui/background.js
gnome-desktop broke API in commit ca5d61cf24, as it didn't *add* a property
as incorrectly stated in the commit message, but *replaced* an existing one.
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1457
https://phabricator.endlessm.com/T27822
> background: Adjust to gnome-desktop API break

- js/ui/iconGridLayout.js
When calling either the destroyCallback or the undoCallback,
Overview doesn't pass any arguments. However, the callbacks
passed by IconGridLayout were expecting an 'info' argument
that never came!
Remove these arguments and simplify the callbacks.
https://phabricator.endlessm.com/T28051
> fixup! iconGridLayout: Add the Endless-specific class IconGridLayout

- js/ui/appDisplay.js
- js/ui/codeView.js
- js/ui/components/clubhouse.js
The use of CLUBHOUSE_ID outside the clubhouse.js file was causing some
problems due to the javascript import and importing cycles, when the
getClubhouseApp function is called in the codeView.js file, the first
time, the CLUBHOUSE_ID is not set yet, so it's undefined and because of
that it's unable to check if the clubhouse is installed.
To fix this problem, this patch changes the use of CLUBHOUSE_ID with a
literal string. Another solution could be to move this id to a new file
to remove the importing cycles, but as we're using it two times, it's
easier to use the literal here.
https://phabricator.endlessm.com/T27778
> Hack: Fix clubhouse import

- js/misc/parentalControlsManager.js
- js/ui/appIconBar.js
- js/ui/components/networkAgent.js
- js/ui/components/polkitAgent.js
- js/ui/iconGridLayout.js
- js/ui/search.js
- js/ui/shellMountOperation.js
This PR contains a few patches that were present in 3.6 and got dropped on the 3.34 rebase. I tested and they seem to work fine.
This should fix the following issues:
- Respect parental controls settings for panel icons - https://phabricator.endlessm.com/T27191
- A fixup for parentalControlsManager fixing the call to `MalContent.Manager.get_app_filter()`
- Reload search providers when parental controls change
- Fix an issue with polkit dialogs not showing up (e.g. Clicking `unlock` in the User settings)
https://phabricator.endlessm.com/T27795
> Backport some leftovers from 3.34 rebase

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/forceAppExitDialog.js
Without either of these changes, hitting Ctrl+Alt+Del yields no dialog
and the following backtrace:
JS ERROR: TypeError: this._launchSystemMonitor is undefined
ForceAppExitDialog<@resource:///org/gnome/shell/ui/forceAppExitDialog.js:85:17
_showForceAppExitDialog@resource:///org/gnome/shell/ui/windowManager.js:2607:22
I do not understand why none of the class's methods are accessible from
within constructor(), but all other subclasses of ModalDialog use the
pattern:
var Foo = GObject.registerClass(
class Foo extends extends ModalDialog.ModalDialog {
_init() {
super._init(...);
so follow that pattern here.
With that change alone, hitting Ctrl+Alt+Del shows a small, square,
empty dialog which cannot be dismissed. This appears to be due to this
assignment:
this.contentLayout.style_class = …
> Fix force quit dialog

- js/ui/codeView.js
The hack-data.ini search paths was calculated in the function creation
so if the clubhouse is not installed, the path will be incorrect and the
keyfile can't be found.
If the user installs the clubhouse, every following call will use that
null keyfile that will cause the problem of the FtH in every window.
This patch moves the search paths calculation to the function returned
to solve this problem and be resilent to clubhouse
installation/uninstallation.
https://phabricator.endlessm.com/T28218
> codeView: move hack-data.ini search paths to the function

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/iconGrid.js
This adds a slight shadow to the icons in the icon grid. This was
previously part of the "Editable Labels" feature which was dropped in
the GNOME 3.34 rebase, but this part needs to be preserved.
In the next rebase, this commit should be moved before commit 0590f9f6
("Implement the desktop search's results panel").
https://phabricator.endlessm.com/T28279
> theme: Add style for icon grid

- js/ui/userMenu.js
The activate signal requires a ClutterEvent object and the call is done
with no params, so it's undefined and this breaks the avatar button in
the user menu, giving this error in the log:
JS ERROR: Error: Wrong type undefined; boxed type ClutterEvent expected
activate@resource:///org/gnome/shell/ui/popupMenu.js:182:9
UserAccountSection</<@resource:///org/gnome/shell/ui/userMenu.js:46:17
This patch fixes this problem passing null as parameter.
https://phabricator.endlessm.com/T28203
> userMenu: Fix open user preferences on avatar click

- js/ui/appDisplay.js
The AllView class has a direct method called selectApp and doesn't have
the view attribute, so this call should be done directly.
https://phabricator.endlessm.com/T28310
> appDisplay: Fix selectApp method

- data/dbus-interfaces/com.endlessm.Payg1.xml
- js/misc/paygManager.js
eos-paygd now emits an ImpendingShutdown signal before initiating a
forced shutdown.[1] Update the D-Bus introspection with the new signal;
this will later be used to give the user warning of the shutdown.[2]
[1] https://github.com/endlessm/eos-payg/pull/65
[2] https://phabricator.endlessm.com/T27134
https://phabricator.endlessm.com/T27133
> paygManager: Update iface for ImpendingShutdown signal

- data/theme/gnome-shell-sass/_endless.scss
Previously, icons were vertically centered within their bin layout.
However, the icon label may take up one or two lines, so that would mean
that icons were staggered vertically when icons with two-line labels
were next to icons with one-line labels.
This can be squashed with 36d607fc3fc1814a19cfab762a41481e74c9d439 on
the next rebase. It's not relevant to upstream since upstream icons only
have one line of text (which ellipsizes a lot less frequently since the
icons are larger.)
https://phabricator.endlessm.com/T28168
> iconGrid: Adjust internal alignment of icon components in icon container

- js/ui/appDisplay.js
This patch sets the custom icon that shows the hack state as drag actor,
by default it was using the Clubhouse icon that doesn't show the on/off
status.
https://phabricator.endlessm.com/T28375
> Hack: Set the custom icon on drag to HackAppIcon

- js/ui/appDisplay.js
Fix the following issue:
JS ERROR: TypeError: this._iconGridLayout is undefined
RenameFolderMenu/<@resource:///org/gnome/shell/ui/appDisplay.js:1936:13
activate@resource:///org/gnome/shell/ui/popupMenu.js:182:9
_onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:135:9
https://phabricator.endlessm.com/T28485
> fixup! js: Delay instantiation of IconGridLayout until it’s needed

- js/ui/codeView.js
There is a problem with the Flip to hack button position when moving the window. The button position is synced with the window on movement, but during the movement the button is hidden and the `queue_relayout` call do nothing, so we need to call the `_synchronizeButton` method after the window movement to ensure that the button is placed correctly.
https://phabricator.endlessm.com/T28535
> fixup! codeView: Add codeview to provide Flip to Hack

- js/ui/status/power.js
I've observed that UPower can occasionally report a charge level of 100%
while the state is still "charging". This usually doesn't last very long
but it is noticeable because the power icon changes to a "missing icon"
icon. This will handle that rare case correctly.
https://phabricator.endlessm.com/T28321
> power: Handle "100% but charging" case

- js/ui/appIconBar.js
Not sure why the arrow was nonetheless drawn on the bottom despite it being specified on the top, but this is why the allocation of the menu items wasn't being calculated correctly.
https://phabricator.endlessm.com/T28471
> Fix bad layout of app icon right click menu

- js/ui/appDisplay.js
The event blocker in AllView is responsible for stealing click events
from the icon grid and closing the folder popup. The event blocker is
kept unreactive when no folder popup is visible, and it's made reactive
as a response to the 'open-state-changed' signal.
Using this signal, though, is problematic. When opening an app folder,
the icon grid first opens space for the folder to fit in; during this
period, it's possible to click on another folder icon, and break the
icon grid state.
Make sure the event blocker is reactive immediately after clicking on
a folder icon.
Related: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1470
Upstream: https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/816
https://phabricator.endlessm.com/T28173
> allView: Ensure event blocker is reactive before popup is open

- data/eos-launch.desktop.in.in
- data/eos-link-feedback.desktop.in.in
- src/shell-app-system.c
I noticed while telling @erikos about `X-Flatpak-RenamedFrom` (for https://github.com/endlessm/hack-toy-apps/pull/328) that the code that implements it predates [this merge request](https://gitlab.gnome.org/GNOME/glib/merge_requests/339) making it into a GLib release, and can now be simplified.
While working on simplifying it, I noticed that two of our downstream `.desktop` files use the old intltool syntax of prefixing translatable fields with `_`. gnome-shell now uses `xgettext` which doesn't work with this syntax; as a result, the installed versions of these `.desktop` files are missing these fields.
```
wjt@camille:~$ cat /usr/share/applications/eos-link-feedback.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Exec=chromium-browser …
```
> Use g_desktop_app_info_get_string_list(); fix two broken .desktop files

- js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T28649
This commit place the flag file inside the user config dir instead of the default path.
This fixup is a follow up of this PR:
https://github.com/endlessm/gnome-shell/pull/594#pullrequestreview-319803683
> fixup! clubhouse: Enable hack-mode for hack1 users

- data/theme/gnome-shell-sass/_endless.scss
The CSS of the notification-banner class changed in common.scss.
https://phabricator.endlessm.com/T28614
> clubhouse: Update CSS to have transparent banner

- js/ui/appDisplay.js
We want the app center icon to read “More Apps”, not “App Center” (or,
heaven forbid, “Software”). Previously, this was set as the GenericName
in our gnome-software's .desktop file, and this custom icon class
attempted to use that as its name.
However, this regressed in the 3.34 rebase. The problem is that
assigning to this._name after chaining up to AppIcon._init() is too
late: AppIcon._init() sets this._name to the non-generic name, then in
turn chains up to ViewIcon._init() which accesses this.name (defined by
AppIcon to return this._name). After a drag, the label for the icon is
correctly re-set to the app center's GenericName.
Fix this by explicitly re-setting the icon's label at the end of
_init(), similarly to how it is re-set after a drag.
Alternative approach to …
> fixup! appDisplay: Add the App Center icon to the grid

- js/ui/appDisplay.js
Right now removing a folder from desktop works but there is no way to
undo the action as is done for non-folder icons.
Given that individual icons can still be removed from a folder and
that the folder gets deleted once the last icon is removed (and
recreated if we undo the removal of the last icon) lets remove this
option for folders for now to avoid confusing user trying to undo
the operation.
https://phabricator.endlessm.com/T29052
> appDisplay: Temporarily disable "Remove from desktop" action for folders

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/components/clubhouse.js
The label bottom margin changed in commit 76bd3e84 from 25px to 30px
to consider the buttons below. But when there are no buttons, the text
looks misaligned.
https://phabricator.endlessm.com/T29046
> clubhouse: Fix vertical aligment of label notification

- js/ui/components/clubhouse.js
The item banner creation callback tries to use the newly created banner
and it's called directly in the constructor so the object doesn't exists
yet and cause an exception.
This patch makes the callback call async so the object will exists when
the callback is called.
There's also a reposition of the itemBanner when a new questBanner
appears and the same for the questBanner to recalculate all banners
positions when there are more than one, this fixes the item notification
position when there's quest notifications, placing that below.
https://phabricator.endlessm.com/T29166
> clubhouse: Fix item notification creation

- data/dbus-interfaces/com.endlessm.Payg1.xml
- data/theme/gnome-shell-sass/_endless.scss
- js/misc/paygManager.js
- js/ui/payg.js
- js/ui/paygUnlockDialog.js
Create a notification on the screenshield that shows
the user which is the related ACCOUNT_ID tied to the computer.
https://phabricator.endlessm.com/T28225
> payg: Add AccountID support for the UI

- js/misc/parentalControlsManager.js
In libmalcontent, MctAppFilterError was renamed to MctManagerError:
https://github.com/endlessm/malcontent/commit/300b5a624f8afde8d3ba250f5b6ff8912d0baa50
That commit includes compatibility defines, but evidently those aren't
working as intended, because gnome-shell is crashing in the latest
master ostree build with this:
Jan 22 15:01:55 endless gnome-shell[4252]: Getting parental controls for user 110
Jan 22 15:01:55 endless gnome-shell[4252]: JS WARNING: [resource:///org/gnome/shell/misc/parentalControlsManager.js 54]: reference to undefined property "GetAppFilterFlags"
Jan 22 15:01:55 endless gnome-shell[4252]: JS ERROR: TypeError: Malcontent.AppFilterError is undefined
ParentalControlsManager<@resource:///org/gnome/shell/misc/parentalControlsManager.js:56:1 …
> parentalControls: Update error domain to prevent crash

- js/misc/parentalControlsManager.js
As with commit 53f510b2, in recent libmalcontent, MctGetAppFilterFlags was also
renamed to MctManagerGetValueFlags:
https://github.com/endlessm/malcontent/commit/300b5a624f8afde8d3ba250f5b6ff8912d0baa50
That commit includes compatibility defines, but evidently those aren't
working as intended via GIR, because gnome-shell is considering all apps as blacklisted
in the latest master ostree build due to this:
```
Jan 22 22:58:08 endless-master gnome-shell[5152]: JS WARNING: [resource:///org/gnome/shell/misc/parentalControlsManager.js 68]: reference to undefined property "GetAppFilterFlags"
Jan 22 22:58:08 endless-master gnome-shell[5152]: JS ERROR: TypeError: Malcontent.GetAppFilterFlags is undefined
ParentalControlsManager</<@resource:///org/gnome/shell/misc/parentalControlsManager.js:68:17 …
```
> parentalControls: Update filter flags domain to prevent having all apps blacklisted

- js/ui/appDisplay.js
Loading an icon folder may fail if the user doesn't have access to the
corresponding `.directory` file or if the file doesn't exist.
https://phabricator.endlessm.com/T29205
> appDisplay: Continue loading icon grid even if an icon folder cant be loaded

- js/ui/appDisplay.js
Also remove folder from icon grid, otherwise it assumes the folder is visible and breaks state (e.g. when creating new folders by drag & drop).
The downside is that the user cannot (easily unless updating gsettings directly) restore the folder - for example by fixing wrong permissions - after restarting the shell, given the new layout will be saved without the folder.
https://phabricator.endlessm.com/T29205
> fixup! appDisplay: Continue loading icon grid even if an icon folder cant be loaded

- debian/endless-session-mods/endless.json
Add the hack extension to the list of extensions of
the Endless session.
https://phabricator.endlessm.com/T28568
This PR depends on:
* https://github.com/endlessm/gnome-shell/pull/630
And requires the eos-hack-extension to be installed to make it work the hack desktop icon: https://github.com/endlessm/eos-hack-extension
The current clubhouse doesn't work with the extension so to make it work we need to use the branch: https://github.com/endlessm/clubhouse/tree/hack-extension
> Add eos-hack@endlessm.com extension

- js/ui/status/payg.js
Trying to update the accountID every time we synced the remaining
time made the weird behaviour of not properly populating it the
first time, discarding the rest of the runs. Now, we only add the
item on  the menu just once, after paygManager has been fully
initialized.
https://phabricator.endlessm.com/T28492
> payg: Properly init accountID menu item

- js/misc/config.js.in
- js/misc/ibusManager.js
This cherry-picks some commits from latest upstream/master and fixes an issue with code trying to access Config.LOCALSTATEDIR that was dropped when removing the watermark extension.
https://phabricator.endlessm.com/T29580
> General fixes

- js/ui/payg.js
- js/ui/screenShield.js
- js/ui/status/automaticUpdates.js
After https://phabricator.endlessm.com/T29401, the notification
banners emitted by the automaticUpdates and the payg classes didn't
work because they depended on an unexpected sessionMode. This fixes
that to the old behaviour.
https://phabricator.endlessm.com/T29582
> payg/automaticUpdates: Fix banner notification

- js/ui/panel.js
Commit 55b57421d replaced signal connections with vfunc calls which
means PanelMenu.Button no longer invokes the _onEvent callback when
clicked. Lets fix that by reimplementing the vfunc_event instead.
https://phabricator.endlessm.com/T29673
> fixup! bottomPanel: Add a shutdown button to the login screen

- src/shell-window-tracker.c
This patch removes the check to ensure that the hack mode is enabled
because that setting is not in the shell anymore. It was moved to the
extension.
We could try to use the shell extension dbus service to check if the hack
mode is enabled, but I think that it's not needed because it'll make the
code a bit complex and the performance improvement will not be great.
To do that we'll need to create a new dbus proxy and keep it alive, so it's
simpler and easier to just continue and try to create the toolbox proxy
for all windows even if the hack mode is disabled.
https://phabricator.endlessm.com/T28568
> fixup! window-tracker: associate toolbox windows with target application

- src/shell-app-cache.c
The app-cache code currently stores the folder translations in a hash
that can be accessed via shell_util_get_translated_folder_name().
This hash uses the filename (inc. extension) for the "desktop-directory"
as key which causes an issue when trying to find the translation
on AppDisplay._findBestFolderName() which gets categories (folder names)
from the app info which doesn't contain the ".directory" extension.
Fix that by storing the filename without extension as the hash key for
the cached folder translations.
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1168
https://phabricator.endlessm.com/T29690
> app-cache: Fix cache for folder translations

- js/ui/appDisplay.js
This basically restores the old behaviour we had on 3.7 and most functionality works from my tests.
Some input issues still present with these changes:
- dragging an icon to an existing folder doesn't work
- sometimes (rarely) dragging icons on top of others won't work (i.e. won't create a folder)
- clicking and holding an icon show 2 menus (background and app context menu)
- dragging an icon outside a folder does nothing (it can be re-positioned inside a folder though)
https://phabricator.endlessm.com/T29682
> Fix most input issues

- data/dbus-interfaces/com.endlessm.Payg1.xml
- data/gnome-shell-dbus-interfaces.gresource.xml
- data/gnome-shell-theme.gresource.xml
- data/theme/gnome-shell-sass/_endless.scss
- data/theme/gnome-shell-sass/_high-contrast-colors.scss
- data/theme/payg-near-expiration-symbolic.svg
- data/theme/payg-normal-symbolic.svg
- js/gdm/authPrompt.js
- js/gdm/loginDialog.js
- js/js-resources.gresource.xml
- js/misc/customerSupport.js
- js/misc/paygManager.js
- js/ui/main.js
- js/ui/messageTray.js
- js/ui/panel.js
- js/ui/payg.js
- js/ui/paygUnlockDialog.js
- js/ui/screenShield.js
- js/ui/sessionMode.js
- js/ui/status/payg.js
- po/POTFILES.in
- src/shell-util.c
- src/shell-util.h
✓ pick 79ee0802f st-private: Add support for letter-spacing in ClutterText based StWidgets
✓ pick 543b6388d st-entry: Set text-related CSS properties on the internal ClutterText
✓ pick 2f9689795 payg: Initial implementation of the PAYG manager component
squash ae2b6ee87 payg: Check if proxy was created
squash 24a54fbea payg: Wait for the PaygManager before showing the screenshield's dialog
squash 7ae9e98d1 payg: Show periodic notifications with the remaining PAYG time
squash b16f98190 payg: Show a notification with the remaining PAYG time on startup
squash 1a41973e5 paygManager: Understand ExpiryTime in terms of CLOCK_BOOTTIME
squash 355602f11 paygManager: make timeRemainingSecs() public
✓ pick a94c3e0e0 payg: Add a new screen to allow unlocking PAYG machines
squash e55326ddb payg: Visual …
> T28780 (PAYG)

- src/st/st-icon.c
Commit c89d6a633 introduced a default fallback icon that would be displayed in case the main gicon or the fallback gicon wasn't set or failed to load.
This broke the use case where a StIcon is created but no main icon or fallback icon are set on purpose, for example the appindicator extension which always creates a StIcon to represent icons in menu items but the actual icons are only set if the application provides one, leaving the menu showing the default fallback ("image-missing") icon for all menu entries that don't actually have an icon provided by the application.
Fix that by only using the default fallback icon if the provided one failed to load.
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1173
https://phabricator.endlessm.com/T29665
> st/icon: Only load default fallback icon if an icon was set and failed to load

- js/ui/appDisplay.js
AppIcon receives only one param on constructor, fix it.
https://phabricator.endlessm.com/T28780
> appDisplay: Fix call to AppIcon constructor

- js/ui/screenShield.js
This change was dropped by mistake during rebase.
Original change from https://github.com/endlessm/gnome-shell/pull/633.
https://phabricator.endlessm.com/T29583
> fixup! payg: Add a new screen to allow unlocking PAYG machines

- data/theme/gnome-shell-sass/_endless.scss
These values now are getting overriden on _app-grid.scss, let's restore the same values used on eos3.7.
https://phabricator.endlessm.com/T28780
> fixup! Adjust app grid icons to Endless

- js/ui/iconGridLayout.js
Support for undo a folder removal is currently not implemented, lets remove
the notification action for now as to not confuse users.
Patch originally from https://phabricator.endlessm.com/T28532 - not strictly needed as currently (not sure if a bug though) we don't show context menus for icon folders, but still possible to be invoked from other places and given IconGridLayout._undoRemoveItem() doesn't support undo'ing folder removal, lets make sure we don't even try.
https://phabricator.endlessm.com/T29782
> iconGridLayout: Temporarily disable "Undo" notification action when removing folders

- js/ui/screenShield.js
Fix "JS ERROR: this._dialog is null" in the log after a valid code is
applied using the tray applet.
> fixup! payg: Add success screen

- js/ui/appDisplay.js
This PR contains 4 patches but only the first one (to fix the vfuncs to return parent results) is actually needed for the fix. I can split the changes in separate PRs if needed, please let me know.
I noticed folder icons never show the background menu and after investigations I noticed the issue was that `vfunc_button_press_event` (and touch-event) were always propagating the events and thus triggering the background action long-press event. Fixed by returning the parent class result for the vfuncs if the event is not handled by AppIcon itself.
This fix may be a good candidate for upstream but I didn't push it yet as I wasn't sure if that is an upstream issue as well given the background action in question here is a downstream only change.
https://phabricator.endlessm.com/T29781
> Do not show background menu when long-pressing app icon

- js/ui/appDisplay.js
shell_app_system_lookup_app() can return NULL, even if the app ID was
returned by shell_app_system_query(). In particular, this can happen
when the executable referenced in the Exec= line of the .desktop file
does not exist. This is because GLib validates whether the Exec= line is
in the path when constructing a GDesktopAppInfo (and returns NULL if
not), but g_desktop_app_info_search() does not validate this before
returning results.
The visible symptom of this bug is that, when a desktop search query
matches such a file, desktop search gets stuck on "Searching…" with the
following backtrace:
JS ERROR: TypeError: app is null
getInitialResultSet/</group<@resource:///org/gnome/shell/ui/appDisplay.js:1112:21
getInitialResultSet/<@resource:///org/gnome/shell/ui/appDisplay.js:1102:27 …
> fixup! js: Add support for parental controls filtering to the desktop

- js/ui/status/payg.js
This prevents a JS error on a 32-bit system when trying to build a
string for the remaining time. If PAYG is disabled, that remaining time
is the highest possible 64-bit value, which overflows the standard
32-bit integer passed to `ngettext()`. It’s meaningless to build the
string if PAYG is disabled.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T28788
---
**Untested** since I don’t have a shell, PAYG or 32-bit test setup. It should be fairly low risk.
> payg: Don’t calculate times if PAYG is disabled

- js/ui/screenShield.js
Currently if PAYG credit expires when you're logged in, you get the
unlock code entry screen. But if credit expires at the gdm login screen,
you don't get it. This is because ScreenShield.lock() has an early
return when you're at the login screen (in which case
Main.sessionMode.isGreeter is true), since in that case the computer is
already locked. Call ScreenShield.showDialog() instead in that case.
https://phabricator.endlessm.com/T29898
> screenShield: Properly show PaygUnlockDialog on login screen

- js/ui/sessionMode.js
When locking the screen the shell switches to the `unlock-dialog` session mode and then it switches back to the previous session mode (in our case the `endless` mode) when the screen is unlocked.
When entering a mode the shell ensures all extensions configured in the `enabledExtensions` for that mode are enabled (as long as `allowExtensions` is also set to `true` for that mode).
It will also disable all extensions that are not configured for that mode and were previously enabled.
The problem here is that our default mode (`endless`) has the hack extension enabled but the `unlock-dialog` mode (mode used when the screen is locked) does not, so the shell disables the
hack extension when locking the screen and re-enables it when unlocking the screen (when it switches back to the `endless` …
> sessionMode: Allow eos-hack-extension to remain enabled when screen is locked

- js/ui/appDisplay.js
This fixes a race condition between an app getting installed from a "Get $app" icon, gnome-software asking the shell to replace the "Get $app" icon with the "$app" icon and the shell app cache getting
updated with the new installed app.
By the time the shell gets the request from gnome-software to replace the "Get $app" icon it tries to reload the folder view which checks if the new $app is available invoking `Shell.AppSystem.get_default().lookup_app()` which checks the app cache but the cache may not have been updated yet with the new app (the cache is updated on a timer triggered by
a file monitor changed signal).
Fix this by making sure to refresh the folder view when the app cache is updated, as is already done by the main app view (AppDisplay).
https://phabricator.endlessm.com/T30108
> appDisplay: Refresh folder view when app cache is updated

- js/ui/screenShield.js
Show the app grid after unlocking when no visible windows are
present. That way, we can avoid the chain of events that end
up resulting in the empty grid.
https://phabricator.endlessm.com/T29817
> screenShield: Show Apps page if necessary after unlocking

- data/eos-link-feedback.desktop.in.in
Use the default browser instead of chromium - we don't need to use chromium anymore given we don't rely on the exploration center existing anymore and instead just redirect users to the forum (which should work on all browsers).
https://phabricator.endlessm.com/T30295
> fixup! project: Add eos-link-feedback back

- js/ui/status/rfkill.js
Cherry-pick of https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/1386, just so I can remove a workaround from the panel extension.
https://phabricator.endlessm.com/T30172
> rfkill: Always sync state on construction

- debian/endless-session-mods/endless.json
So it's automatically enabled, and undisablable.
https://phabricator.endlessm.com/T30540
> List eos-desktop@endlessm.com in Endless session

- src/st/st-theme-node-drawing.c
- src/st/st-theme-node-private.h
- src/st/st-theme-node.c
Add these changes back (cherry-pick from 3.8, unmodified) as needed by the panel extension for the endless button CSS style.
https://phabricator.endlessm.com/T30445
> st: Implement more CSS gradient options

- js/ui/sessionMode.js
We want the customized panel to be available on gdm and lockscreen mode as well.
https://phabricator.endlessm.com/T30445
> sessionMode: Enable the panel extension on gdm and lockscreen mode

- js/ui/sessionMode.js
Keep the eos-desktop extension enabled on the lock screen.
Nowadays the desktop extension can handle tearing down
fine, but the act of destroying and recreating the app
grid is a heavy one and incurs stuttering when unlocking
the screen.
https://phabricator.endlessm.com/T30623
> Enable eos-desktop extension on lock screen as well

- data/dbus-interfaces/com.endlessm.Payg1.xml
- data/gnome-shell-dbus-interfaces.gresource.xml
- data/gnome-shell-theme.gresource.xml
- data/theme/gnome-shell-sass/_endless.scss
- data/theme/payg-near-expiration-symbolic.svg
- data/theme/payg-normal-symbolic.svg
- js/gdm/loginDialog.js
- js/js-resources.gresource.xml
- js/misc/customerSupport.js
- js/misc/paygManager.js
- js/ui/main.js
- js/ui/panel.js
- js/ui/payg.js
- js/ui/paygUnlockDialog.js
- js/ui/screenShield.js
- js/ui/sessionMode.js
- js/ui/shellDBus.js
- js/ui/status/payg.js
- po/POTFILES.in
- src/shell-util.c
- src/shell-util.h
Changes here depend on (are on top of) https://github.com/endlessm/gnome-shell/pull/690.
This PR includes the following:
- **pick** 7d4512ea5 payg: Initial implementation of the PAYG manager component
- small conflict mainly on build system
- **pick** ca6825e79 payg: Add a new screen to allow unlocking PAYG machines
- small conflict on build system
- also changed the default panel layout for the "unlock-dialog-payg" session mode to not include the "powerMenu" indicator (as it was in the original commit). The reason is that upstream does not have the "powerMenu" indicator (functionality included in the "aggregateMenu" upstream which is also included in the default layout when on "unlock-dialog-payg" session mode) and we want this layout to work if the panel extension is disabled (the panel …
> Re-add PAYG support

- js/ui/viewSelector.js
- meson.build
- src/meson.build
- src/shell-app-system.c
This PR includes:
- **pick** dfa64aada4  shell-app-system: Report an event when an application opens/closes
- small conflict on build system
- sends `SHELL_APP_IS_OPEN_EVENT` metric
- **pick** 1e349a1304  viewSelector: Record metric when user initiates a desktop search
- reworked the patch a bit to adjust to upstream changes
- sends  `EVENT_DESKTOP_SEARCH` metric
Tested and both events above are sent as expected.
Apart from those we also had the following metrics on 3.8:
- `SHELL_APP_ADDED_EVENT`:  when an app was added to the grid
- `SHELL_APP_REMOVED_EVENT`: as above but when removed from the grid
Given we don't support adding/removing apps to/from grid anymore I did not include those.
https://phabricator.endlessm.com/T30661
> Re-add metrics support to new shell

- js/ui/appDisplay.js
Backport of https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1428
Together with https://github.com/endlessm/eos-desktop-extension/pull/15, helps with the grid and the clones getting out of sync.
https://phabricator.endlessm.com/T30623
> Redisplay when page changes

- data/dbus-interfaces/meson.build
- data/dbus-interfaces/org.gnome.Shell.AppLauncher.xml
- data/eos-launch.desktop.in.in
- data/gnome-shell-dbus-interfaces.gresource.xml
- data/meson.build
- js/misc/eos-launch.js
- js/misc/meson.build
- js/ui/shellDBus.js
Reworked changes to not depend on downstream `AppActivation` support. The `AppActivation` support was responsible for handling the integration with the speedwagon as well as to ensure the `X-Endless-Maximized` desktop key was respected. Both speedwagon and `X-Endless-Maximized` will be dropped on 3.9 so let's simplify the launcher impl.
Also fixed a small issue where `eos-launch` would try launching (and report an error) the locale specific apps even if the app requested had already launched successfully (can be easily reproduced on 3.8 by clicking on "Give Us Feedback" on Help Center and looking at the journal).
https://phabricator.endlessm.com/T30293
https://phabricator.endlessm.com/T30172
> eos-launch: Add launcher for 'endlessm-app://' schemes

- js/ui/appDisplay.js
BaseAppView not disconnecting from the 'app-filter-changed'
signal means parental controls may trigger callbacks on
a destroyed grid, which tries to access destroyed icons,
which spams the journal with stack traces.
Disconnect from parental controls when BaseAppView is destroyed.
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1441
> appDisplay: Disconnect from parental controls on destroy

- debian/endless-session-mods/endless.json
We've changed the name for the `eos-hack` and `eos-onboarding` extensions, to use the new `endlessos.org` domain.
https://phabricator.endlessm.com/T30888
https://phabricator.endlessm.com/T30887
> Rename hack and onboarding extensions

- js/ui/screenShield.js
When this payg was applied after the 3.38 rebase, the changes to the
activate() function were applied in the wrong place. Bring back the
early return introduced by commit f02feca1f "screenShield: Fix use of
null this._dialog" on the eos3.8 branch. This means gnome-shell will
correctly still show gnome-initial-setup after resuming from suspend.
Locking for PAYG still works as _ensureUnlockDialog() will return true
in the session modes where we need to lock.
https://phabricator.endlessm.com/T30915
> fixup! payg: Integrate with screen shield and GDM screen

- data/theme/gnome-shell-sass/_endless.scss
- js/ui/background.js
This partially reverts commit 9d0025bdfb6c92fcf4a69e99309abc6300718c1d
"Update default background color for login and lock screens".
For the new bootsplash animation we are going to stick with upstream's
current background color and texture.
https://phabricator.endlessm.com/T32724
> Revert to default background color from upstream

- src/calendar-server/gnome-shell-calendar-server.c
app_notify_events_added uses an intermediate builder to construct an
array that is then added to the main variant using g_variant_builder_add
which should clear the intermediate, but doesn't due to the way it is
passed: by value, rather than as a pointer.
This was debugged with the help of Eduardo Habkost, who believes it
works on x86 due to big structs being passed as pointers.
Fixed: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3440
Part-of: <https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1848>
(cherry picked from commit 404ca91941226faaf2479609f0109244e66d4bcd)
(cherry picked from commit f212512c0e877222837c6816bbef24369a2edc86)
https://phabricator.endlessm.com/T32772
> calendar-server: Fix double-free detection abort

- js/ui/payg.js
- js/ui/paygUnlockDialog.js
- payg: Replace 'code' with 'keycode' in user-facing strings
- payg: Improve language on user-facing strings
- payg: Explicitly mention the expected keycode length
https://phabricator.endlessm.com/T32864
https://phabricator.endlessm.com/T31749
> payg: Small UI improvements

- js/ui/paygUnlockDialog.js
This causes a regression where the PAYG unlock dialog doesn't
show up, which is pretty bad considering this screenshield is
what's shown during initial setup.
This commit should be squashed on commit 96cf95a6b "payg: Add PAYG
infrastructure" during the next rebase.
https://phabricator.endlessm.com/T33021
> payg: Port PaygUnlockDialog to new MetaIdleAdd API

- src/shell-app-system.c
The aggregate_key parameter has been removed from the API.
This should be squashed into 37d580ba276bc5336d85f35a84e0736e4e2a9298
("shell-app-system: Report application times") in the next rebase.
Depends on https://github.com/endlessm/eos-metrics/pull/47
https://phabricator.endlessm.com/T33252
> shell-app-system: Adjust start_aggregate_timer call

- data/meson.build
- src/calendar-server/meson.build
- subprojects/extensions-app/data/meson.build
- subprojects/extensions-app/data/metainfo/meson.build
- subprojects/extensions-tool/src/templates/meson.build
Unlike other targets that take a name, i18n.merge_file() does not.
Part-of: <https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2078>
(cherry picked from commit 65450a836ee9e0722a2d4c3327f52345eae293c6)
gnome-shell is currently failing to build:
```
Executing subproject extensions-tool 
extensions-tool| Project name: gnome-extensions-tool
extensions-tool| Project version: 41.2
extensions-tool| C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
extensions-tool| C linker for the host machine: cc ld.bfd 2.35.2
extensions-tool| Dependency gio-2.0 found: YES 2.70.4 (cached)
extensions-tool| Dependency gio-unix-2.0 found: YES 2.70.4 (cached)
extensions-tool| Run-time dependency gnome-autoar-0 found: YES 0.4.3
extensions-tool| Run-time dependency …
```
> build: Drop incorrect positional arg

- data/dbus-interfaces/com.endlessm.Payg1.xml
- js/misc/paygManager.js
- js/ui/payg.js
- js/ui/paygUnlockDialog.js
Make use of the CodeLength D-Bus property on eos-paygd's interface to
inform the user how many characters should be entered.
This commit should be squashed on commit 96cf95a6b "payg: Add PAYG
infrastructure" during the next rebase.
https://phabricator.endlessm.com/T33325
> payg: UI support for backends with different code lengths

- js/ui/welcomeDialog.js
An Endless OS user will likely not be familiar with the term GNOME.
I took a quick look at whether we could use some field of
/etc/os-release rather than hardcoding "Endless OS 5" here. The short
answer is no. All fields of os-release that have a version number
contain the full x.y.z.
PRETTY_NAME is supposed to be:
> A pretty operating system name in a format suitable for presentation
> to the user. May or may not contain a release code name or OS version
> of some kind, as suitable.
>
> Example: "PRETTY_NAME="Fedora 17 (Beefy Miracle)"".
Ours is:
PRETTY_NAME="Endless OS 5.0.0"
But if we change this to "Endless OS 5", the full 5.y.z version number
will no longer be visible in Settings → About. The BUILD_ID (OSTree
build timestamp) is shown there, but this is less useful than the
version …
> welcomeDialog: Welcome users to Endless OS, not GNOME

- data/org.gnome.Shell@wayland.service.in
- data/org.gnome.Shell@x11.service.in
When GNOME shell runs on a less memory system (for example 3 GB RAM), it is usually killed by the kernel OOM-killer easily. Because, it has a higher OOM score. However, GNOME desktop environment cannot do anything when the GNOME shell is killed.
This commit adjusts and lowers down gnome-shell process' OOM score to avoid being killed by the kernel OOM-killer too early. In other words, sacrifices other processes first.
https://phabricator.endlessm.com/T34139
> data: Lower down gnome-shell process' OOM score

- js/ui/welcomeDialog.js
Anecdotally, a sample of 1 user reported having reflexively skipped the
tour. It would be interesting to know what proportion of users takes the
tour.
The event will be recorded together with the current OS version (like
all others) and the image ID, which tells us the originally-installed OS
version, so a simple boolean is enough for us to measure what proportion
of new/upgrading/all users took or skipped the tour.
https://phabricator.endlessm.com/T34473
> welcomeDialog: Record whether the tour is launched or skipped

- js/ui/extensionDownloader.js
- js/ui/extensionSystem.js
Historically we’ve defined it as ‘endless’ (e.g.
`XDG_CURRENT_DESKTOP=endless:GNOME`). We’re now looking to standardise the desktop ID, and for that it would be better if it were capitalised like other desktop IDs.
See: https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/73
> extensions: Allow desktop ID to be ‘endless’ or ‘Endless’

- debian/endless-session-modes/endless.json
We have removed the extension from the OS.
Listing it here when it is not installed does not seem to cause any
harm, but it can't do any good either.
https://phabricator.endlessm.com/T35054
> Remove Hack from 'endless' session mode

- js/ui/appDisplay.js
- js/ui/appFavorites.js
- src/shell-app-system.c
- src/shell-app-system.h
At the moment, this pull request is bringing back the following patches, removing references to `X-Endless-Alias`:
- ~563b2f1 shell-app-system: Add support for X-Endless-Alias key in desktop files~ (removed, squashed with the next patch)
- 407f304 shell-app-system: obey X-Flatpak-RenamedFrom
- 4f4fc58 appDisplay: compare possibly-changed apps more thoroughly
- b04b91d shell-app-system: extract deep comparison for GDesktopAppInfo
- 26a98c3 appFavorites: respect X-Endless-Alias and X-Flatpak-RenamedFrom
It is a draft while I look around for an opportunity to better align with upstream.
https://phabricator.endlessm.com/T35065
> T35065 handle app renaming

- debian/endless-session-modes/endless.json
We are removing this from the OS.
This is very lightly used, not enough to justify updating it for GNOME
43 compatibility.
If we wish to bring this functionality back in future, we should instead
package https://pagure.io/background-logo-extension, which is actually
the ancestral source of the eos-watermark-extension code and which is
actively maintained by a core Shell developer for each Fedora release.
https://phabricator.endlessm.com/T35077
> Remove eos-watermark from 'endless' session mode

- js/misc/keyboardManager.js
- js/ui/status/keyboard.js
- meson.build
- src/meson.build
- src/shell-util.c
- src/shell-util.h
In past versions of Endless OS, we added the concept of a “password mode” to
GNOME Shell, which is triggered either within GNOME Shell's own password
fields, or from applications by setting a D-Bus property on the shell. In this
mode, Shell would check whether any configured input source could type the
English letters a through z, and if not, append the US English keyboard layout
to the list of available sources. The intent is to ensure, for example, that it
is possible to type Wi-Fi passwords, which typically use only English ASCII
letters even in regions where the local language uses some other script, even
if the user's keyboard layout is (say) Thai.
This approach requires coöperation from applications (which we previously
patched GNOME Initial Setup to do, for example) and does not …
> keyboard: Ensure a Latin layout is always available

- js/ui/layout.js
- js/ui/overviewControls.js
The [first patch](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/7a5f1e5c9e96b04a41407d1ae9d9f242b31ed1cf) is part of upstream 45.0 and newer.
The second was [accepted upstream](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3422) and will be in 47.beta.
https://phabricator.endlessm.com/T34453
> Backport two upstream fixes for startup animation

- js/ui/layout.js
- js/ui/overview.js
- js/ui/overviewControls.js
Requires corresponding changes in eos-desktop-extension:
- https://github.com/endlessm/eos-desktop-extension/pull/99
----
During session startup, we have the following chain:
LayoutManager._prepareStartupAnimation()
`- LayoutManager._startupAnimation()
`- LayoutManager._startupAnimationComplete()       (a)
| or
`- LayoutManager._startupAnimationGreeter()        (b)
| or
`- LayoutManager._startupAnimationSession()        (c)
`- Overview.runStartupAnimation()               (d)
`- OverviewActor.runStartupAnimation()       (e)
`- ControlsManager.runStartupAnimation()  (f)
Branch (b) calls LayoutManager._startupAnimationComplete() once the
animation is complete. Branch (c) does the same, except that
ControlsManager.runStartupAnimation() is an async function that awaits …
> Make startup animation use async functions throughout

- js/ui/status/payg.js
The string “Enter unlock code…” was not marked for translation since
d50cd8dc60f400882db9ce425da13003b0561965 which reworked this interface
for the newer quick settings menu.
https://phabricator.endlessm.com/T35611
> fixup! payg: Add panel indicator for PAYG account details and actions
