endlessm/gnome-shell

js/misc/ibusManager.js, js/misc/keyboardManager.js, js/ui/appDisplay.js, js/ui/dateMenu.js, js/ui/edgeDragAction.js, js/ui/endSessionDialog.js, js/ui/notificationDaemon.js, js/ui/viewSelector.js, js/ui/windowManager.js, src/gnome-shell-extension-prefs.c, src/gnome-shell-plugin.c, src/gnome-shell-portal-helper.c, src/main.c, src/run-js-test.c, src/shell-global-private.h, src/shell-global.c
Do this in preparation for the GJS upgrade, even before the rebase.
https://phabricator.endlessm.com/T16757
=> Backport patches from GNOME Shell 3.24 for GJS 1.48

data/Makefile.am, data/eos-launch.desktop.in.in, js/Makefile.am, js/misc/eos-launch.js, js/ui/shellDBus.js
https://phabricator.endlessm.com/T1388
https://phabricator.endlessm.com/T2212
=> Implements a simple application launcher program that handles 'endlessm-app://' schemes

data/org.gnome.shell.gschema.xml.in, js/js-resources.gresource.xml, js/ui/appActivation.js, js/ui/main.js, js/ui/windowAttentionHandler.js, js/ui/windowManager.js, src/shell-app.c, src/shell-window-tracker.c, src/shell-window-tracker.h
https://phabricator.endlessm.com/T2212
=> Implement the AppActivation feature with Speedwagon integration 

js/ui/endlessButton.js
The Endless button should act as the Super key, which toggles between
the apps view and the last opened window.
https://phabricator.endlessm.com/T17227
=> endless-button: Toggle apps when pressed

data/org.gnome.shell.gschema.xml.in, js/js-resources.gresource.xml, js/ui/main.js, js/ui/watermark.js
This is not a simple copy-paste of the Watermark extension,
but a fully-integrated watermark manager with verious settings
to tweak the UI.
https://phabricator.endlessm.com/T15839
=> watermark: introduce Watermak in GNOME Shell

js/ui/panelMenu.js
The first commit is a good-to-have one backported from 3.24 and the second one is the actual fix.
https://phabricator.endlessm.com/T17228
=> Fix hidden calendar popup on low resolutions

js/ui/overview.js
When there are no applications opened and the user presses the super key
or clicks the Endless button, we show a dialog with a message informing
about that.
https://phabricator.endlessm.com/T17227
=> overview: Show dialog when toggling apps with no applications opened

js/ui/windowManager.js
The new animations make windows minimize and unminimize from
the bottom of the screen, as well as making the Speedwagon
windows animate from the bottom of the screen when they're
mapped.
https://phabricator.endlessm.com/T17526
=> window-manager: implement Endless animations

js/ui/status/power.js
https://phabricator.endlessm.com/T17546
=> power: make indicator visible when appropriate

js/js-resources.gresource.xml, js/ui/components/appStore.js, js/ui/main.js, js/ui/sessionMode.js, js/ui/shellDBus.js, js/ui/sideComponent.js, js/ui/windowManager.js
We use the old App Store to add folders and websites to the desktop, so add the relevant component back.
https://phabricator.endlessm.com/T17236
=> Add integration with the old App Store 

js/ui/appDisplay.js, js/ui/dash.js, js/ui/overviewControls.js, js/ui/search.js, js/ui/viewSelector.js
We merged https://github.com/endlessm/gnome-shell/pull/42 prematurely to have some testing early enough, but some issues slipped in, so this is mainly a PR to correct those before we keep adding stuff. 
https://phabricator.endlessm.com/T17230
=> Fixup branch to correct some issues with PR #42

js/ui/viewSelector.js
Fallout from rebasing the feed branch.
=> viewSelector: create feed button for clones too

data/theme/gnome-shell.css, js/ui/appDisplay.js, js/ui/iconGrid.js
This PR makes some changes to make the desktop look more EOS-ish, with the grid of icons properly spaced and centered and the icons being of the right size.
https://phabricator.endlessm.com/T17658
=> Style changes for the desktop's icon grid

js/js-resources.gresource.xml, js/ui/components/updaterManager.js, js/ui/sessionMode.js
The code was mostly just copied over from eos-shell.
https://phabricator.endlessm.com/T17656
=> Add the updaterManager

js/ui/appDisplay.js
Don't load all the apps first and then the folders, but respect the
order in the GSettings key under org.gnome.shell.icon-grid-layout.
https://phabricator.endlessm.com/T17815
=> appDisplay: Load apps and folders in order as stored in GSettings

js/ui/appDisplay.js, js/ui/iconGrid.js
https://phabricator.endlessm.com/T17658
=> appDisplay, iconGrid: Fix unwanted scrollbars inside folder popups

data/theme/gnome-shell.css, js/ui/appDisplay.js, js/ui/search.js, js/ui/viewSelector.js
https://phabricator.endlessm.com/T17659
=> Implement the EOS style for the search results panel

js/ui/watermark.js
Per T15841, the watermark file path is specified in the
gnome-shell.conf file in /var/eos-image-defaults/branding
folder.
The current code, however, is not aware of this file and
does not read from it. This causes the FNDE (and potential
future branded images) to not be loaded.
Fix that by also reading from the gnome-shell.conf file.
Notice that setting a GSettings file patch overrides the
custom file.
https://phabricator.endlessm.com/T15839
=> watermark: Read from custom config as well

js/ui/layout.js, js/ui/overview.js
https://phabricator.endlessm.com/T18019
=> Fix out-of-sync clones after DnD operations

js/ui/overview.js, js/ui/viewSelector.js
A very tricky PR, it fixes the problems observed during startup (window picker mode, can't do DnD...) while trying not to cause any regressions. Not 100% sure this is the perfect approach, but after many different attempts and tests this is the smallest patch set that I could get that seems to improve the situation without breaking things. 
https://phabricator.endlessm.com/T17789
=> Fix problems with the startup process

js/ui/appDisplay.js
Make sure non-empty folders can't be removed neither via the contextual
menu on right-click nor by dropping them onto the bin (AppCenter icon).
https://phabricator.endlessm.com/T18029
=> appDisplay: Prevent non-empty folders from being removed

data/org.gnome.shell.gschema.xml.in
For now, until we have enough content for it to be meaningful.
https://phabricator.endlessm.com/T18017
=> gschema: disable discovery feed for all languages

data/theme/gnome-shell.css
We need to remove the border we get from the default StEntry style.
https://phabricator.endlessm.com/T17774
=> theme: fix search entry border

data/theme/gnome-shell.css
https://phabricator.endlessm.com/T18035
=> Keep the label centered when dragging an app icon

js/ui/appDisplay.js, js/ui/notificationDaemon.js
When there are new notifications from the app (e.g. the ChatBox notifies the user regarding certain lessons) a badge is added to the desktop icon.
=> Desktop icons: add notification information

js/ui/discoveryFeedButton.js
https://phabricator.endlessm.com/T18546
=> discoveryFeedButton: Disable on < 1024 screen widths

js/ui/iconGrid.js
When calculating the row that the user is hovering with the dragged
icon, the current implementation of the paginated icon grid does not
take into account the extra space opened for folders, and ends up
miscalculating the target row.
Fix that by storing and using the opened extra space. This is
implemented by an overrided function to keep IconGrid logic
isolated from PaginatedIconGrid details.
https://phabricator.endlessm.com/T18038
=> paginatedIconGrid: consider opened space when calculating dnd

js/ui/discoveryFeedButton.js, js/ui/viewSelector.js
https://phabricator.endlessm.com/T18546
=> discoveryFeedButton: Handle resolution changes

js/ui/appIconBar.js
https://phabricator.endlessm.com/T18350
=> Consider scale factor when creating the app icons in the taskbar

js/ui/appDisplay.js
We read the X-Endless-Replaced-By key in order to work out
which apps should be replaced.
https://phabricator.endlessm.com/T18771
=> appDisplay: Filter out placeholder app-store apps

data/org.gnome.shell.gschema.xml.in
https://phabricator.endlessm.com/T17773
=> feed: Enable discovery feed for Indonesian on all images

data/org.gnome.shell.gschema.xml.in
https://phabricator.endlessm.com/T17773
=> feed: Enable for english, too

js/ui/ctrlAltTab.js, js/ui/panel.js
Change the title and flip the icon vertically to reflect reality.
https://phabricator.endlessm.com/T19368
=> Adapt 'Top Bar' to become 'Bottom Bar' for the Ctrl+Alt+Tab dialog

js/ui/layout.js, js/ui/legacyTray.js, js/ui/messageTray.js, js/ui/monitor.js, js/ui/overview.js, js/ui/panel.js, js/ui/workspaceThumbnail.js, src/st/st-scroll-view.c
This PR reverts a patch for this issue that was not actually fixing the problem since more changes were needed both in the shell (which were [changes that got lost during the previous rebase](https://github.com/endlessm/eos-shell/pull/2354/commits)) and in mutter itself.
Instead of doing that, it picks a patch from Jonas Adahl attached to [GNOME Bug 730551](https://bugzilla.gnome.org/show_bug.cgi?id=730551) that, along with the patches for mutter attached there, does actually fix the problem without more changes needed in the shell.
https://phabricator.endlessm.com/T19389
=> Improve handling being headless

src/shell-app.c
Replace our downstream patch with the one recently landed upstream
https://phabricator.endlessm.com/T19424
=> Don't transition to STOPPED while still in the STARTING state 

js/ui/status/bluetooth.js
https://phabricator.endlessm.com/T19638
=> bluetooth: Fix inconsistent state when coming back from suspend

js/ui/windowManager.js
https://phabricator.endlessm.com/T19659
=> Fix strange animation to the left when unminimizing windows

js/ui/layout.js, js/ui/overview.js, js/ui/viewSelector.js
https://phabricator.endlessm.com/T19778
=> Handle the overview on startup-prepared, not on startup-complete

js/ui/appDisplay.js, src/shell-app.c, src/shell-app.h
https://phabricator.endlessm.com/T18933
=> Retrieve the App Center's name for the desktop from the desktop file

js/ui/shellDBus.js
This got regressed with commit 59451795, should be squashed with that
commit in future rebases.
https://phabricator.endlessm.com/T19913
=> shellDBus: Don't append icons that already exist in AddAppIfNotVisible

js/misc/util.js
At the moment we were matching the text inserted in the search bar against
non trivial regular expression ANY time that the search terms changed, which
is pretty aggressive on the CPU, easily getting the shell into an apparently
"locked-up" state, especially for longer searchs strings.
Fortunately, we can do some optimizations here to prevent this situations:
1. If the term is a valid URI in that it's possible to parse at least
its scheme and host fields, it's considered a valid URL "as-is".
2. Else, if the term is a generic string exceeding the maximum length
specified then we simply ignore it and move onto the next term.
3. In any other case (non-URI term, valid length) we match the term
passed against the regular expression to determine if it's a URL.
Turns out it's a bit hard to find …
=> Avoid executing RegExps to find URLs in the search bar whenever possible

js/ui/layout.js, js/ui/overview.js, js/ui/viewSelector.js
https://phabricator.endlessm.com/T19824
=> Fix brusque animations showing/hiding the Overview

data/vendor-customer-support.ini, js/gdm/authPrompt.js
https://phabricator.endlessm.com/T20297
=> Implement password reset salting

data/theme/gnome-shell.css, js/ui/panelMenu.js
This commit just tweaks the background colors when hovering
and activating the bottom bar buttons.
Should be merged with a0a5fd38cc4 at the next rebase.
https://phabricator.endlessm.com/T20327
=> style: More theming tweaks

js/ui/layout.js, js/ui/overview.js, js/ui/windowManager.js, js/ui/workspaceMonitor.js
This should fix the regression caused by the patch from commit ef744c3, reported internally in https://phabricator.endlessm.com/T20661, and probably https://phabricator.endlessm.com/T20577 too.
https://phabricator.endlessm.com/T20577
https://phabricator.endlessm.com/T20661
=> Fix icon grid flashing when closing side components

js/ui/userMenu.js
Per Endless design specs...
From:
- All Settings...
- Online Accounts
- Help Center
To:
- Settings
- Social Accounts
- Help
https://phabricator.endlessm.com/T20800
=> userMenu: simplify menu item text

js/js-resources.gresource.xml, js/ui/components/paygManager.js, js/ui/main.js
It simply proxies all the calls, signals and properties changes
between the shell and the eos-payg daemon.
https://phabricator.endlessm.com/T21607
=> payg: Initial implementation of the PAYG manager component

data/theme/gnome-shell-sass/_endless.scss, js/js-resources.gresource.xml, js/misc/paygManager.js, js/ui/main.js, js/ui/paygUnlockDialog.js, js/ui/screenShield.js, js/ui/sessionMode.js, po/POTFILES.in, src/st/st-entry.c, src/st/st-private.c
This will communicate with the com.endlessm.Payg1 D-Bus service and allow unlocking machines where the current PAYG has expired, as well as react to changes in the PAYG state of the machine.
https://phabricator.endlessm.com/T21608
=> payg: Implement an unlock dialog for PAY and integrate it with the lock screen

data/theme/gnome-shell-sass/_endless.scss, js/ui/paygUnlockDialog.js
https://phabricator.endlessm.com/T21841
=> Use the right text strings for the PAYG unlock dialog

js/misc/paygManager.js, js/ui/paygUnlockDialog.js
https://phabricator.endlessm.com/T21808
=> Gracefully handle com.endlessm.Payg1.Error.TooManyAttempts

js/misc/paygManager.js, po/POTFILES.in
Note: This PR also includes a fixup for a previous commit.
https://phabricator.endlessm.com/T21848
=> Implement PAYG notifications as a reminder for expiration time 

data/theme/gnome-shell-sass/_endless.scss, js/gdm/authPrompt.js, js/js-resources.gresource.xml, js/misc/customerSupport.js, js/ui/main.js, js/ui/paygUnlockDialog.js
https://phabricator.endlessm.com/T21864
=> payg: Allow defining overrides for text in the unlock dialog

js/ui/status/automaticUpdates.js
https://phabricator.endlessm.com/T21683
=> fixup! Introduce Automatic Updates indicator

src/shell-app-system.c
Not doing so will cause trouble when launching an application via a .desktop
file if multiple .desktop files are associated to the same executable and the
one being used is not the main one (e.g. gnome-user-accounts-panel.desktop,
instead of the main gnome-control-panel.desktop file), because the ShellApp
instance will remain forever in the starting_apps map, confusing the shell
whenever the ShellAppSystem API to check running apps is used.
This should be squashed along with ac005f84 in future rebases.
https://phabricator.endlessm.com/T21146
=> shell-app-system: Remove apps from the "starting apps" list when stopped

js/ui/status/automaticUpdates.js
For consistency with other menus such as VPN and Bluetooth.
https://phabricator.endlessm.com/T22316
=> automaticUpdates: Simplify turn on/off label

js/ui/appActivation.js, js/ui/codeView.js
https://phabricator.endlessm.com/T23224
=> T23224: Skip maximization effect when synchronizing actor state

js/ui/codeView.js
https://phabricator.endlessm.com/T23226
=> codeview: Don't show button while lock screen is active

src/wobbly-effect.cpp
We want the model size to be based on the size of the window
including its shadows, but we do not want that to include any
affine transformations currently done on the window, which
clutter_actor_get_paint_box will perform on the volume before
projecting it and getting its bounding box.
This commit assumes that the paint volume without any effects applied
is two dimensional and orthogonal.
https://phabricator.endlessm.com/T23034
=> wobbly: Only query the untransformed paint box when resizing model

js/ui/codeView.js
https://phabricator.endlessm.com/T23236
=> T23236: Start builder once the animation is finished

config.h.meson, js/ui/runDialog.js, meson.build, src/shell-app.c, src/shell-util.c, src/shell-util.h
Please merge and wait for build completion of https://github.com/endlessm/glib/pull/46 before merging this
https://phabricator.endlessm.com/T23273
=> Improved app launching via posix_spawn

js/ui/windowManager.js
Revert change on master until we can work out why the packaging changes didn't get pulled in.
https://phabricator.endlessm.com/T23314
=> Revert T23314

meson.build, src/meson.build, src/wobbly-effect.c
https://phabricator.endlessm.com/T23534
=> build: Switch to using libanimation instead of libwobbly

js/ui/windowManager.js
https://phabricator.endlessm.com/T23314
=> T23314: Unrevert support for AnimationsDbus

src/wobbly-effect.c
Now that clutter correctly computes the paint volume during
effects as the paint volume *up to* the current effect, there's
no need to override the get_paint_volume vfunc and lie about
the paint box.
https://phabricator.endlessm.com/T23692
=> wobbly: Remove paint box override hack

data/theme/gnome-shell-sass/_endless.scss
Let the label be free to adjust itself according to the allocated size.
https://phabricator.endlessm.com/T23147
=> theme: Don't hardcode search result width

data/theme/gnome-shell-sass/_endless.scss, js/js-resources.gresource.xml, js/ui/calendar.js, js/ui/components/clubhouse.js, js/ui/messageTray.js, js/ui/notificationDaemon.js, js/ui/sessionMode.js, src/shell-util.c, src/shell-util.h
This component will "catch" notifications coming from the Clubhouse app and display them in a different way than the regular ones, in fact implementing the Clubhouse's Quest View.
https://phabricator.endlessm.com/T23931
=> Add Clubhouse component

js/ui/codeView.js
https://phabricator.endlessm.com/T24036
=> Add com.endlessm.OperatingSystemApp to whitelist

js/ui/components/clubhouse.js
Or we will segfault later in case it isn't.
https://phabricator.endlessm.com/T24097
=> clubhouse: only enable component when clubhouse is installed

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T24064
=> clubhouse: position notification banner at the top right

js/ui/components/clubhouse.js
Make sure they're on the primary monitor by taking its X coordinate
into account when positioning them.
https://phabricator.endlessm.com/T24206
=> clubhouse: move button/banner on the primary monitor

js/ui/switcherPopup.js
https://phabricator.endlessm.com/T24191
=> switcherPopup: Bind to the stage, not the monitor

js/js-resources.gresource.xml, js/misc/soundServer.js, js/ui/codeView.js
https://phabricator.endlessm.com/T24173
This depends on https://github.com/endlessm/hack-sound-server/pull/17
=> sounds: Add FlipToHack sounds

js/ui/codeView.js
Same scheme as in the codeview to gracefully handle a sound being
stopped before the UUID arrives.
https://phabricator.endlessm.com/T24523
=> codeView: Add hover loops for flip-to-hack button

js/ui/codeView.js
This looks in the location where com.endlessm.HackComponents should
install the hack-data.ini file. If the file isn't there, or doesn't
contain the relevant key, then nothing is blacklisted. This is
important, so that things still work in case the HackComponents flatpak
is uninstalled.
If the file does contain the key, then the app ID (whether from Flatpak
or an installed .desktop file) is checked against the blacklist, and if
it is present in the blacklist, then the CodeViewManager should not
handle mapping that window.
https://phabricator.endlessm.com/T24416
=> codeView: Implement flip-to-hack blacklist

js/ui/codeView.js
https://phabricator.endlessm.com/T24486
=> codeView: Play sound when flip animation starts

js/js-resources.gresource.xml, js/misc/parentalControlsManager.js, js/ui/appDisplay.js, js/ui/backgroundMenu.js, js/ui/iconGridLayout.js, js/ui/remoteSearch.js, js/ui/shellDBus.js, src/shell-util.c, src/shell-util.h
https://phabricator.endlessm.com/T24016
=> T24016 Support parental filtering of desktop launchers

data/theme/gnome-shell-sass/_endless.scss
The images inside the notification have changed size. Change the
margins to make the characters sit at the bottom of the message box.
https://phabricator.endlessm.com/T24814
=> data: Adapt CSS of Clubhouse notifications

js/js-resources.gresource.xml, js/misc/soundServer.js, js/ui/codeView.js, js/ui/components/clubhouse.js, js/ui/soundable.js
https://phabricator.endlessm.com/T24716
=> clubhouse: Hook up sounds for entry button

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T24783
=> clubhouse: Align clubhouse button with FtH button

data/gnome-shell-theme.gresource.xml, data/theme/clubhouse-notification-button-next-symbolic.svg, data/theme/gnome-shell-sass/_endless.scss, js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T24874
=> T24874 next button

data/theme/gnome-shell-sass/_endless.scss
Match styling with the same message in the clubhouse app.
- Change color and width of action buttons
- Soften shadows
- Fix size of white box
- Reposition and change color of the x close button
- Move character image up 1 pixel to sit on top of the message border
https://phabricator.endlessm.com/T24966
=> clubhouse: Polish styling of the notification

js/ui/codeView.js
Temporarily, we want to whitelist only the apps that can be flipped in
Episode 1.
If the whitelist key is missing or empty, then everything should be
whitelisted. This way, we can just empty the key in the config file when
we want to lift this restriction.
https://phabricator.endlessm.com/T24655
=> codeview: Add whitelist for flip-to-hack apps

data/theme/gnome-shell-sass/_endless.scss
And enlarge the content box to allow 5 lines in the label.
https://phabricator.endlessm.com/T25018
=> clubhouse: Style, have space between label and Next button

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T24876
=> clubhouse: Add looping sound for pulsing button state

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T25236
=> clubhouse: Play pulse sound only if highlighted button visible

js/ui/components/clubhouse.js, js/ui/messageList.js
https://phabricator.endlessm.com/T25192
=> T25192 richtext

js/ui/codeView.js
https://phabricator.endlessm.com/T26045
=> codeView: Monitor changes on hack-data file

js/ui/codeView.js, js/ui/windowManager.js
https://phabricator.endlessm.com/T25788
=> codeView: Hide toolbox and FtH on wobble movement

js/ui/codeView.js
When a hack app is destroyed when it's minimized the corresponding
CodingSession is not removed from the list because the function
handleDestroyWindow is never called and this cause problems in the
future because there's a CodingSession with an app that points to a non
existing window.
To fix this we need to listen the actor destroy event and remove the
CodingSession if this happens.
https://phabricator.endlessm.com/T25880
=> codeView: remove CodingSession on actor destroy

js/ui/components/networkAgent.js
This needs to be squashed with ff636dc058 at the next rebase.
https://phabricator.endlessm.com/T26608
=> networkAgent: Add missing import

data/dbus-interfaces/com.endlessm.HackableApp.xml, data/dbus-interfaces/com.endlessm.HackableAppsManager.xml, data/gnome-shell-dbus-interfaces.gresource.xml, js/ui/codeView.js, js/ui/main.js, js/ui/shellDBus.js
Provides a property to list the apps that are currently hackable
https://phabricator.endlessm.com/T26547
=> shellDBus: Add HackableAppsManager DBus interface

js/ui/layout.js, js/ui/sideComponent.js
https://phabricator.endlessm.com/T26597
=> fixup! sideComponent: Add SideComponent back

data/dbus-interfaces/meson.build, data/dbus-interfaces/org.gnome.Shell.AppLauncher.xml, data/eos-launch.desktop.in.in, data/gnome-shell-dbus-interfaces.gresource.xml, data/meson.build, js/misc/eos-launch.js, js/misc/meson.build, js/ui/appActivation.js, js/ui/shellDBus.js
https://phabricator.endlessm.com/T26726
=> Reintroduce Shell API to launch applications

js/ui/codeView.js
https://phabricator.endlessm.com/T26928
=> X-Endless-Hackable

js/ui/shellEntry.js
Update the shell's search-entry hint text if the default
internet provider is enabled or disabled via parental controls.
https://phabricator.endlessm.com/T26991
=> shellEntry: Update shell entry if browsers are disabled

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T27190
=> T27190 Stop tracking windows

js/ui/altTab.js, js/ui/boxpointer.js, js/ui/dateMenu.js, js/ui/dialog.js, js/ui/status/network.js, src/st/st-texture-cache.c, src/st/st-widget.c
A light series of trivial cherry-picks, synchronizing our fork with `gnome-3-32` and adding https://github.com/endlessm/gnome-shell/commit/2715aadc9cda5168696ef3d023bca06d582dcc25 on top.
https://phabricator.endlessm.com/T27210
=> Upstream cherry-picks

js/ui/appDisplay.js, js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T27245
=> appDisplay: Fix spinning cursor when clicking on Hack icon

js/ui/appIconBar.js
~~No specific task but being handled at https://phabricator.endlessm.com/T27191.~~
~~See https://phabricator.endlessm.com/T27191#735731 for details on how to reproduce the crash.~~
https://phabricator.endlessm.com/T27279
Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>
=> AppIconMenu: Disconnect from parent actor signals when the actor is destroyed

js/ui/codeView.js
https://phabricator.endlessm.com/T27274
=> codeView: Make it work with hack katamari flatpak

js/ui/discoveryFeedButton.js
This is to clearly separate the two flows.
https://phabricator.endlessm.com/T27305
=> Hack, PinnedApp: remove DiscoveryFeed tab

data/dbus-interfaces/com.hack_computer.HackableApp.xml, data/dbus-interfaces/com.hack_computer.HackableAppsManager.xml, data/gnome-shell-dbus-interfaces.gresource.xml, js/ui/shellDBus.js
Rename hack dbus interfaces as well.
https://phabricator.endlessm.com/T27400
=> Hack2 deploy: rename hack dbus interfaces

debian/changelog
This will be the version we'll be based on for a
few days.
https://phabricator.endlessm.com/T27794
=> Update changelog to 3.32.2

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T27972
=> clubhouse: Remove clip on notification after slideIn

po/ar.po, po/en_CA.po, po/en_GB.po, po/fr.po, po/hi.po, po/hr.po, po/is.po, po/pa.po, po/pt_BR.po, po/zh_TW.po
I have removed
The newlines
That were in
The strings
https://phabricator.endlessm.com/T27764
=> Updates from Transifex

js/ui/appDisplay.js, js/ui/iconGridLayout.js
The two string changes in 977bab512ba4e8e272363c708009f19d6df37144 were lost in the rebase.
https://phabricator.endlessm.com/T16267
https://phabricator.endlessm.com/T28181
=> Reapply string changes lost in rebase.

js/ui/components/networkAgent.js
https://phabricator.endlessm.com/T28190
=> Fix regression in VPN password dialog

js/ui/appActivation.js, js/ui/iconGrid.js
https://phabricator.endlessm.com/T28196
=> Fix regression with spash screen not closing

js/ui/backgroundMenu.js
…use cases
We now create folders by dragging one icon over another.
https://phabricator.endlessm.com/T17881
https://phabricator.endlessm.com/T28154
=> Drop the "Add Folder" desktop menu item

data/org.gnome.shell.gschema.xml.in, js/ui/appDisplay.js, js/ui/shellDBus.js
https://phabricator.endlessm.com/T27905
=> Hack: Make hack icon removable

data/gnome-shell-theme.gresource.xml, data/theme/feedback-symbolic.svg, js/ui/userMenu.js
https://phabricator.endlessm.com/T27926
=> T27926: add "Give Us Feedback" back to user menu

data/dbus-interfaces/meson.build, data/dbus-interfaces/org.gnome.Shell.AppLauncher.xml, data/eos-launch.desktop.in.in, data/gnome-shell-dbus-interfaces.gresource.xml, data/meson.build, js/misc/eos-launch.js, js/misc/meson.build, js/ui/shellDBus.js
This change was lost during rebase, lets reinstate it.
https://phabricator.endlessm.com/T28309
=> Fix endlessm-app:// links handling

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T28312
=> clubhouse: Fix notifications with no buttons

js/ui/dnd.js, js/ui/iconGrid.js
https://phabricator.endlessm.com/T28156
=> Fix dragging icon past end of icon grid

js/ui/appDisplay.js
https://phabricator.endlessm.com/T27905
Rebase notes:
This can be squashed with:
419f1346 Hack: Make hack icon removable
=> Hack: Fix HackAppIcon remove action

js/ui/shellMountOperation.js
https://phabricator.endlessm.com/T28343
=> fixup! passwordMode: add keyboard layout switcher for password entries

js/ui/appDisplay.js
https://phabricator.endlessm.com/T28365
=> Fix creating folders with knowledge apps

data/theme/gnome-shell-sass/_endless.scss, js/ui/components/clubhouse.js
- Add CSS class to item notifications
- CSS: Add margin to the right to avoid colliding with the x button
- CSS: Set square size to item icon
https://phabricator.endlessm.com/T28392
=> clubhouse: Improve styling of item notifications

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T28384
=> clubhouse: use priority field to mark a dialogue cancellable

js/ui/appDisplay.js
https://phabricator.endlessm.com/T27905
=> fixup! Hack: Make hack icon removable

js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T28470
=> clubhouse: Dialogues should not be ellipsized

js/ui/altTab.js
https://phabricator.endlessm.com/T28510
=> fixup! altTab: do not show inactive hack session windows

js/ui/iconGridLayout.js, js/ui/messageTray.js
https://phabricator.endlessm.com/T28532
=> Fix undo action when removing apps from desktop

js/ui/components/clubhouse.js
The migration quest is not launched by default because the
hack-mode-enabled is false by default so we need to set to true for
old hack users.
https://phabricator.endlessm.com/T27473
=> clubhouse: Enable hack-mode for hack1 users

js/misc/util.js, js/ui/dateMenu.js
https://phabricator.endlessm.com/T28167
=> Weather forecast improvements

js/ui/appDisplay.js
A partial backport of https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/841 (two of the commits there don't apply to our codebase) and a minor cleanup.
https://phabricator.endlessm.com/T28801
=> Backport of gnome-shell!841

data/theme/gnome-shell-sass/_endless.scss, js/ui/components/clubhouse.js
https://phabricator.endlessm.com/T28800
=> clubhouse: Button to move dialogue up / down

js/ui/appDisplay.js
https://phabricator.endlessm.com/T28729
=> Hack: Add tooltip to hack icon

js/ui/components/clubhouse.js
If the notifications are added right away, the icon might be still
loading, and a placeholder (the app icon) appears instead. This is
because we have animated characters as icons. The issue is specially
noticeable the first time the characters load, on low-end devices like
the Hack computer.
This fixes the issue by adding the notification to the chrome in a
callback, which is called when the icon is loaded.
https://phabricator.endlessm.com/T28565
=> clubhouse: Add notifications to the layout when ready

data/theme/gnome-shell-sass/_endless.scss, js/ui/appDisplay.js
Remove hardcoded newlines from the tooltip label, and instead A. set a
fixed width to the tooltip box and B. enable wrapping of text in the
tooltip description label.
https://phabricator.endlessm.com/T28841
https://phabricator.endlessm.com/T29075
=> Hack: Improve tooltip of Hack button

js/gdm/authPrompt.js
The new generated reset code will last until the user logs in again,
which happens automatically after the user changes the password once
it gets the unlock code and enters it in GDM or if the user remembers
the old password and logs in again.
https://phabricator.endlessm.com/T27921
https://phabricator.endlessm.com/T27290
=> passwordReset: Make password reset codes last across a reboot

js/ui/messageTray.js
https://phabricator.endlessm.com/T13041
=> js/messageTray: null-check notification to prevent double destroy

js/ui/status/payg.js
Show the account ID coming from the daemon on the user's
icon tray, along with the time remaining.
https://phabricator.endlessm.com/T28492
Do not merge until https://github.com/endlessm/gnome-shell/pull/614 is properly merged.
=> payg: Add AccountID info on the applet

debian/changelog, debian/endless-session-mods/endless.json, debian/gnome-shell-common.install
(A copy of https://github.com/endlessm/gnome-shell/pull/625)
https://phabricator.endlessm.com/T29401
=> debian: Add a endless custom session mode

debian/endless-session-mods/endless.json
Add the watermark extension to the list of extensions of
the Endless session.
https://phabricator.endlessm.com/T28778
=> Add eos-watermark@endlessm.com extension

js/ui/altTab.js, js/ui/unlockDialog.js
https://phabricator.endlessm.com/T28780
=> Fix some regressions

data/eos-link-feedback.desktop.in.in, data/meson.build, data/theme/gnome-shell-sass/_endless.scss, js/ui/appDisplay.js, js/ui/discoveryFeedButton.js, js/ui/forceAppExitDialog.js, js/ui/internetSearch.js, js/ui/shellEntry.js, js/ui/viewSelector.js
https://phabricator.endlessm.com/T28780
=> Some fixups

js/ui/appDisplay.js, src/shell-app-system.c
https://phabricator.endlessm.com/T29660
=> Fix crash when reloading app grid

js/ui/appDisplay.js, js/ui/iconGrid.js, src/st/st-theme-node-drawing.c, src/st/st-theme-node-private.h, src/st/st-theme-node.c
This one is future proof! It uses the solution proposed upstream, and reverts the revert instead of cherry-picking the original commit.
https://phabricator.endlessm.com/T29687
=> T29687 (alternative solution)

js/misc/paygManager.js, js/ui/payg.js
https://phabricator.endlessm.com/T29698
=> Fix warnings and missing import

js/ui/appDisplay.js
https://phabricator.endlessm.com/T29754
=> Sync folder dialog entry/label and folder icon label when renaming folder

js/ui/payg.js, js/ui/status/payg.js
https://phabricator.endlessm.com/T25995
=> T25995 PAYG time remaining string fixes

js/ui/screenShield.js
https://phabricator.endlessm.com/T29527
=> T29527 Fix resuming from suspend during FBE

data/dbus-interfaces/org.gnome.Shell.InputSourceManager.xml, data/gnome-shell-dbus-interfaces.gresource.xml, js/gdm/authPrompt.js, js/misc/keyboardManager.js, js/ui/components/networkAgent.js, js/ui/components/polkitAgent.js, js/ui/shellMountOperation.js, js/ui/status/keyboard.js, meson.build, src/meson.build, src/shell-util.c, src/shell-util.h
Fallout from the last rebase.
https://phabricator.endlessm.com/T29997
=> passwordMode: add keyboard layout switcher for password entries

js/ui/screenShield.js, js/ui/shellDBus.js
https://phabricator.endlessm.com/T29763
=> T29763 payg unlock dialog fixes

js/ui/paygUnlockDialog.js, js/ui/screenShield.js
https://phabricator.endlessm.com/T29994
=> T29994 Focus PAYG unlock code entry by default

js/ui/paygUnlockDialog.js, js/ui/screenShield.js
https://phabricator.endlessm.com/T28534
=> T28534 Fix PAYG permanent unlock dialog

data/eos-link-feedback.desktop.in.in
https://phabricator.endlessm.com/T30295
=> eos-link-feedback: Point to forum instead of eos-exploration-center feedback page

debian/endless-session-mods/endless.json
https://phabricator.endlessm.com/T30445
=> List eos-panel@endlessm.com in Endless session

debian/gnome-shell-common.install
Needed for customer support to install `40-gdm.rules`. Cherry-picked from eos3.8.
Should be merged together with https://github.com/endlessm/gnome-shell/pull/690.
https://phabricator.endlessm.com/T30648
=> Install /usr/share/polkit-1

js/ui/status/payg.js
This includes the following updates:
- Always keep status in sync when session mode changes (e.g. the menu sensitivity is correctly updated after unlocking the screen if the lock code was entered while the screen was locked)
- Always show account id menu item if supported
- Properly handle destroy (The parent class SystemIndicator doesn't define '_onDestroy')
- Reuse existing payg manager instance
https://phabricator.endlessm.com/T30647
=> General improvements/fixes for PAYG indicator

debian/endless-session-mods/endless.json
https://phabricator.endlessm.com/T30650
=> Add Force Quit Dialog extension to Endless session

data/theme/gnome-shell-sass/_endless.scss, js/ui/components/networkAgent.js
Do not ellipsize text.
**NOTE: Do not merge this just yet as we are on freeze.**
https://phabricator.endlessm.com/T29725
=> fixup! networkAgent: Add switch button for metered connections

js/gdm/authPrompt.js
https://phabricator.endlessm.com/T30685
=> authPrompt: Update pwd reset instructions

debian/endless-session-mods/endless.json
https://phabricator.endlessm.com/T30237
=> List eos-onboarding@endlessm.com in Endless session

js/ui/environment.js
Backport of https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1461.
https://phabricator.endlessm.com/T30597
=> environment: Handle @content for property transitions

data/theme/gnome-shell-sass/widgets/_misc.scss, docs/reference/shell/shell-docs.sgml, js/dbusServices/screencast/screencastService.js, js/gdm/authPrompt.js, js/misc/systemActions.js, js/ui/appDisplay.js, js/ui/dash.js, js/ui/dateMenu.js, js/ui/iconGrid.js, po/fr.po, src/shell-global.c, src/st/st-entry.c
Straight backport of https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1447.
https://phabricator.endlessm.com/T30808
=> Backport app grid drag & drop fixes

js/ui/appDisplay.js, js/ui/iconGrid.js
A clean, conflictless backport of https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1477 (yay for not having downstream patches touching any of these files! \o/)
=> Multiline app titles on hover

js/ui/appDisplay.js, js/ui/appFavorites.js, src/shell-app-system.c, src/shell-app-system.h
https://phabricator.endlessm.com/T31115
=> Readd X-Flatpak-Renamed-From

js/misc/modemManager.js, js/ui/appDisplay.js, js/ui/audioDeviceSelection.js, js/ui/components/telepathyClient.js, js/ui/messageTray.js, js/ui/status/remoteAccess.js, js/ui/windowManager.js, src/shell-screenshot.c
A bunch of cherry-picks. 18f29ea is important to avoid a crash. fc6d997 loosely depends on https://github.com/endlessm/eos-panel-extension/pull/21.
https://phabricator.endlessm.com/T31129
=> 3.38 cherry-picks

debian/changelog, debian/gnome-shell.install
Packaging changes for https://github.com/endlessm/gnome-shell/pull/738.
https://phabricator.endlessm.com/T34300
=> T34300 eos: Reset dynamic-workspaces key on EOS 4 → 5 transition (packaging changes)

data/dbus-interfaces/com.endlessm.Payg1.xml, data/gnome-shell-dbus-interfaces.gresource.xml, data/gnome-shell-theme.gresource.xml, data/theme/gnome-shell-sass/_endless.scss, data/theme/gnome-shell-sass/widgets/_quick-settings.scss, data/theme/payg-near-expiration-symbolic.svg, data/theme/payg-normal-symbolic.svg, js/gdm/loginDialog.js, js/js-resources.gresource.xml, js/misc/customerSupport.js, js/misc/paygManager.js, js/ui/main.js, js/ui/panel.js, js/ui/payg.js, js/ui/paygUnlockDialog.js, js/ui/screenShield.js, js/ui/sessionMode.js, js/ui/shellDBus.js, js/ui/status/payg.js, po/POTFILES.in, src/shell-util.c, src/shell-util.h
https://phabricator.endlessm.com/T35064
-----
I kept my bigger changes on top of the old patches in separate `fixup!` commits to make reviewing a bit easier - so we don't mix up old mistakes and new mistakes :b Please autosquash before merging.
=> T35064 add payg patches
